// 400 daily prompts across 9 categories
// Used for the daily reflection section — 5 prompts per day, seeded by date

export type PromptCategory =
  | "Relationships & Communication"
  | "Career & Purpose"
  | "Self & Identity"
  | "Habits, Growth & Discipline"
  | "Money & Security"
  | "Loss, Grief & Hard Times"
  | "Faith, Meaning & Big Questions"
  | "Anxiety, Mental Health & Wellbeing"
  | "Parenting & Family";

export type DailyPrompt = {
  id: number;
  text: string;
  category: PromptCategory;
};

export const DAILY_PROMPTS: DailyPrompt[] = [
  // RELATIONSHIPS & COMMUNICATION (60)
  { id: 1, text: "My partner and I keep having the same argument. How do we break the cycle?", category: "Relationships & Communication" },
  { id: 2, text: "I feel like I'm always the one who reaches out first. Is this friendship worth keeping?", category: "Relationships & Communication" },
  { id: 3, text: "How do I tell someone I love them without scaring them off?", category: "Relationships & Communication" },
  { id: 4, text: "My sibling and I haven't spoken in two years. Should I be the one to reach out?", category: "Relationships & Communication" },
  { id: 5, text: "I feel invisible in my own family. How do I change this dynamic?", category: "Relationships & Communication" },
  { id: 6, text: "How do I stop taking my frustration out on the people closest to me?", category: "Relationships & Communication" },
  { id: 7, text: "I don't know how to fight fair. What does healthy conflict actually look like?", category: "Relationships & Communication" },
  { id: 8, text: "My friend says things that are funny but always sting a little. Is that a red flag?", category: "Relationships & Communication" },
  { id: 9, text: "I've been ghosted by someone I really cared about. How do I make sense of it?", category: "Relationships & Communication" },
  { id: 10, text: "How do I reconnect with someone after a long silence?", category: "Relationships & Communication" },
  { id: 11, text: "I feel like I give more than I receive in most of my relationships. What do I do with that?", category: "Relationships & Communication" },
  { id: 12, text: "My partner doesn't show affection the way I need. How do I bring it up?", category: "Relationships & Communication" },
  { id: 13, text: "I have a hard time trusting people. Where does that come from?", category: "Relationships & Communication" },
  { id: 14, text: "How do I stop being passive-aggressive and just say what I mean?", category: "Relationships & Communication" },
  { id: 15, text: "Someone I care about is in a relationship I think is bad for them. Do I say something?", category: "Relationships & Communication" },
  { id: 16, text: "I always seem to attract the same type of person. How do I change that pattern?", category: "Relationships & Communication" },
  { id: 17, text: "How do I apologize to someone who doesn't want to hear it?", category: "Relationships & Communication" },
  { id: 18, text: "I'm lonely even though I have people around me. What's missing?", category: "Relationships & Communication" },
  { id: 19, text: "My father and I have never had a real conversation. Is it too late to try?", category: "Relationships & Communication" },
  { id: 20, text: "How do I stop comparing my relationship to everyone else's?", category: "Relationships & Communication" },
  { id: 21, text: "I feel like I lose myself when I'm in a relationship. How do I stay me?", category: "Relationships & Communication" },
  { id: 22, text: "My coworker takes credit for my ideas. How do I handle this professionally?", category: "Relationships & Communication" },
  { id: 23, text: "I'm bad at receiving help. Why is that so hard for me?", category: "Relationships & Communication" },
  { id: 24, text: "How do I tell a friend their advice isn't helpful without hurting them?", category: "Relationships & Communication" },
  { id: 25, text: "I have a tendency to push people away when I get close. How do I stop?", category: "Relationships & Communication" },
  { id: 26, text: "How do I stay friends with someone after a falling out?", category: "Relationships & Communication" },
  { id: 27, text: "My parents don't respect my life choices. How do I handle the holidays?", category: "Relationships & Communication" },
  { id: 28, text: "I feel responsible for everyone else's emotions. How do I put that down?", category: "Relationships & Communication" },
  { id: 29, text: "I keep ending up in friendships where I'm the therapist. How do I find balance?", category: "Relationships & Communication" },
  { id: 30, text: "How do I know if I should forgive someone or just move on?", category: "Relationships & Communication" },
  { id: 31, text: "My partner and I have different values about money. How do we handle this?", category: "Relationships & Communication" },
  { id: 32, text: "I said something I can't take back. How do I repair the damage?", category: "Relationships & Communication" },
  { id: 33, text: "I never know what to say when someone is grieving. How do I show up?", category: "Relationships & Communication" },
  { id: 34, text: "How do I build deeper friendships as an adult? It feels impossible.", category: "Relationships & Communication" },
  { id: 35, text: "I think I'm codependent. What does that actually mean and what do I do?", category: "Relationships & Communication" },
  { id: 36, text: "I feel like my family only calls me when they need something. How do I address that?", category: "Relationships & Communication" },
  { id: 37, text: "How do I tell someone their behavior is affecting me without making it a fight?", category: "Relationships & Communication" },
  { id: 38, text: "I have a friend who is always negative. How much is too much?", category: "Relationships & Communication" },
  { id: 39, text: "My ex reached out after a year. Should I respond?", category: "Relationships & Communication" },
  { id: 40, text: "How do I stop people-pleasing in my relationships?", category: "Relationships & Communication" },
  { id: 41, text: "I feel like I can't be honest with anyone in my life. Why is that?", category: "Relationships & Communication" },
  { id: 42, text: "How do I set a boundary with someone I depend on?", category: "Relationships & Communication" },
  { id: 43, text: "I don't feel heard in my relationship. How do I change that?", category: "Relationships & Communication" },
  { id: 44, text: "My teenager won't talk to me. How do I keep the door open?", category: "Relationships & Communication" },
  { id: 45, text: "How do I tell someone I've outgrown the friendship?", category: "Relationships & Communication" },
  { id: 46, text: "I feel jealous of my friend's success. How do I handle this honestly?", category: "Relationships & Communication" },
  { id: 47, text: "My partner and I want different things for the future. What now?", category: "Relationships & Communication" },
  { id: 48, text: "How do I rebuild trust after I've broken it?", category: "Relationships & Communication" },
  { id: 49, text: "I'm in a relationship that looks good from the outside but feels empty. What do I do?", category: "Relationships & Communication" },
  { id: 50, text: "How do I love someone without trying to fix them?", category: "Relationships & Communication" },
  { id: 51, text: "I have trouble letting people in. What am I really afraid of?", category: "Relationships & Communication" },
  { id: 52, text: "My parent is aging and I don't know how to handle this emotionally.", category: "Relationships & Communication" },
  { id: 53, text: "How do I support a friend who is struggling without burning myself out?", category: "Relationships & Communication" },
  { id: 54, text: "I feel like I've been carrying a grudge for years. How do I let it go?", category: "Relationships & Communication" },
  { id: 55, text: "I'm not sure I actually like the person I've been dating. How do I know?", category: "Relationships & Communication" },
  { id: 56, text: "How do I reconnect with my partner after a rough season?", category: "Relationships & Communication" },
  { id: 57, text: "Someone close to me died and I never got to say what I needed to say.", category: "Relationships & Communication" },
  { id: 58, text: "How do I have a hard conversation I've been avoiding for months?", category: "Relationships & Communication" },
  { id: 59, text: "I feel like I'm always the peacemaker. What's that costing me?", category: "Relationships & Communication" },
  { id: 60, text: "My friendship group has fractured. What do I do?", category: "Relationships & Communication" },

  // CAREER & PURPOSE (55)
  { id: 61, text: "I've been in the same job for seven years and I'm bored. Is that enough reason to leave?", category: "Career & Purpose" },
  { id: 62, text: "I don't know what I'm actually good at. How do I figure that out?", category: "Career & Purpose" },
  { id: 63, text: "How do I ask for what I'm worth without feeling greedy?", category: "Career & Purpose" },
  { id: 64, text: "I got passed over for a promotion and I'm angry. What do I do with this?", category: "Career & Purpose" },
  { id: 65, text: "I want to start something on my own but I'm terrified to leave my salary.", category: "Career & Purpose" },
  { id: 66, text: "How do I deal with a boss who micromanages everything I do?", category: "Career & Purpose" },
  { id: 67, text: "I went back to school and I'm not sure it was the right call. How do I keep going?", category: "Career & Purpose" },
  { id: 68, text: "I feel like I'm working really hard but not getting anywhere. What am I missing?", category: "Career & Purpose" },
  { id: 69, text: "How do I find meaning in work that doesn't feel meaningful?", category: "Career & Purpose" },
  { id: 70, text: "I've been offered a job that pays more but I'd hate the work. What do I do?", category: "Career & Purpose" },
  { id: 71, text: "How do I deal with imposter syndrome that never seems to go away?", category: "Career & Purpose" },
  { id: 72, text: "I want to change careers at 40. Is it too late?", category: "Career & Purpose" },
  { id: 73, text: "I was laid off and I don't know who I am without my job.", category: "Career & Purpose" },
  { id: 74, text: "How do I build a reputation at work without playing politics?", category: "Career & Purpose" },
  { id: 75, text: "I have a business idea I can't stop thinking about. How do I know if it's real?", category: "Career & Purpose" },
  { id: 76, text: "I feel like I'm chasing someone else's version of success. What's mine?", category: "Career & Purpose" },
  { id: 77, text: "How do I stop overthinking and just make a career decision?", category: "Career & Purpose" },
  { id: 78, text: "I hate networking. Do I have to get good at it to get ahead?", category: "Career & Purpose" },
  { id: 79, text: "I'm overqualified for the jobs I can get and underqualified for the ones I want.", category: "Career & Purpose" },
  { id: 80, text: "How do I handle a toxic workplace I can't leave right now?", category: "Career & Purpose" },
  { id: 81, text: "I've been freelancing for two years and I'm exhausted. What am I doing wrong?", category: "Career & Purpose" },
  { id: 82, text: "How do I lead people without feeling like a fraud?", category: "Career & Purpose" },
  { id: 83, text: "I feel pressure to be ambitious, but I just want a simple life. Is that okay?", category: "Career & Purpose" },
  { id: 84, text: "I want to do creative work but I'm afraid I'll never make money at it.", category: "Career & Purpose" },
  { id: 85, text: "How do I stop letting fear run my career decisions?", category: "Career & Purpose" },
  { id: 86, text: "I've been unemployed for six months and I'm losing confidence. How do I stay sharp?", category: "Career & Purpose" },
  { id: 87, text: "My coworker is threatened by me and is making my life difficult. What do I do?", category: "Career & Purpose" },
  { id: 88, text: "How do I stay motivated when the work feels endless?", category: "Career & Purpose" },
  { id: 89, text: "I feel guilty for wanting more. Is that normal?", category: "Career & Purpose" },
  { id: 90, text: "I've built a career I'm good at but don't care about. Where do I start over?", category: "Career & Purpose" },
  { id: 91, text: "How do I handle a performance review that felt unfair?", category: "Career & Purpose" },
  { id: 92, text: "I want to pitch a big idea at work but I'm afraid of being dismissed.", category: "Career & Purpose" },
  { id: 93, text: "How do I build a skill I've always wanted but never prioritized?", category: "Career & Purpose" },
  { id: 94, text: "I'm a high achiever and I still feel like I haven't done enough. What's that about?", category: "Career & Purpose" },
  { id: 95, text: "How do I separate my self-worth from my work performance?", category: "Career & Purpose" },
  { id: 96, text: "I work with someone who takes all the energy out of the room. How do I cope?", category: "Career & Purpose" },
  { id: 97, text: "How do I ask for flexibility at work without seeming uncommitted?", category: "Career & Purpose" },
  { id: 98, text: "I've been doing someone else's job along with mine for a year. How do I address it?", category: "Career & Purpose" },
  { id: 99, text: "I just got a great opportunity but the timing is terrible. What do I do?", category: "Career & Purpose" },
  { id: 100, text: "How do I build momentum on a goal I've started and stopped three times?", category: "Career & Purpose" },
  { id: 101, text: "I'm afraid if I show how ambitious I am, people won't like me.", category: "Career & Purpose" },
  { id: 102, text: "How do I know when to push through and when to quit?", category: "Career & Purpose" },
  { id: 103, text: "I've been told I need more \"executive presence.\" What does that actually mean?", category: "Career & Purpose" },
  { id: 104, text: "I feel invisible at work. How do I change that?", category: "Career & Purpose" },
  { id: 105, text: "How do I stop taking work stress home with me?", category: "Career & Purpose" },
  { id: 106, text: "I want to give feedback to my boss. Is that possible?", category: "Career & Purpose" },
  { id: 107, text: "I've been told I'm too intense at work. Is that something I should change?", category: "Career & Purpose" },
  { id: 108, text: "How do I maintain integrity when the culture at work rewards cutting corners?", category: "Career & Purpose" },
  { id: 109, text: "I got my dream job and I'm not happy. What does that mean?", category: "Career & Purpose" },
  { id: 110, text: "How do I take a real vacation without spiraling about everything I'm missing?", category: "Career & Purpose" },
  { id: 111, text: "I've been a stay-at-home parent for five years and I want to go back to work. How?", category: "Career & Purpose" },
  { id: 112, text: "How do I deal with creative blocks when my livelihood depends on it?", category: "Career & Purpose" },
  { id: 113, text: "I have two career paths in front of me and I genuinely don't know which one is right.", category: "Career & Purpose" },
  { id: 114, text: "How do I build confidence in a new role I feel underprepared for?", category: "Career & Purpose" },
  { id: 115, text: "I said something in a meeting that came out wrong and I can't shake it.", category: "Career & Purpose" },

  // SELF & IDENTITY (55)
  { id: 116, text: "I don't feel like I know who I am anymore. How do I find that again?", category: "Self & Identity" },
  { id: 117, text: "I've spent my whole life trying to please everyone. How do I stop?", category: "Self & Identity" },
  { id: 118, text: "How do I know the difference between low self-esteem and realistic self-assessment?", category: "Self & Identity" },
  { id: 119, text: "I feel like I wear a different mask for everyone I know. Is that bad?", category: "Self & Identity" },
  { id: 120, text: "How do I stop needing external validation to feel okay?", category: "Self & Identity" },
  { id: 121, text: "I'm deeply insecure about something I can't change. How do I make peace with it?", category: "Self & Identity" },
  { id: 122, text: "I feel like I'm just going through the motions. How do I feel alive again?", category: "Self & Identity" },
  { id: 123, text: "How do I build genuine self-confidence, not just fake it?", category: "Self & Identity" },
  { id: 124, text: "I think I have depression but I'm not sure. What are the signs?", category: "Self & Identity" },
  { id: 125, text: "I keep self-sabotaging right before something good happens. Why?", category: "Self & Identity" },
  { id: 126, text: "How do I stop letting what other people think control what I do?", category: "Self & Identity" },
  { id: 127, text: "I feel like I'm fundamentally different from everyone around me. What do I do with that?", category: "Self & Identity" },
  { id: 128, text: "How do I stop numbing out with my phone, food, or alcohol?", category: "Self & Identity" },
  { id: 129, text: "I don't feel worthy of good things. Where does that come from?", category: "Self & Identity" },
  { id: 130, text: "How do I stop minimizing my own needs?", category: "Self & Identity" },
  { id: 131, text: "I've been anxious my whole life and I'm tired of it. Where do I start?", category: "Self & Identity" },
  { id: 132, text: "I feel stuck between who I was and who I want to be. How do I move through that?", category: "Self & Identity" },
  { id: 133, text: "How do I develop my own opinions instead of just adopting everyone else's?", category: "Self & Identity" },
  { id: 134, text: "I feel like I've lost my sense of humor. How do I get it back?", category: "Self & Identity" },
  { id: 135, text: "I'm grieving a version of my life that never happened. Is that real grief?", category: "Self & Identity" },
  { id: 136, text: "How do I stop apologizing for everything?", category: "Self & Identity" },
  { id: 137, text: "I feel like I have to earn the right to rest. How do I unlearn that?", category: "Self & Identity" },
  { id: 138, text: "I compare myself to everyone and it's making me miserable. How do I stop?", category: "Self & Identity" },
  { id: 139, text: "I don't know what makes me happy anymore. How do I figure that out?", category: "Self & Identity" },
  { id: 140, text: "How do I get better at sitting with discomfort instead of running from it?", category: "Self & Identity" },
  { id: 141, text: "I feel like a burden to people who love me. How do I work through this?", category: "Self & Identity" },
  { id: 142, text: "How do I let go of an identity that no longer fits who I am?", category: "Self & Identity" },
  { id: 143, text: "I've spent years being \"the strong one.\" I'm exhausted. What now?", category: "Self & Identity" },
  { id: 144, text: "How do I build a relationship with myself?", category: "Self & Identity" },
  { id: 145, text: "I know what I should do, but I never do it. What's blocking me?", category: "Self & Identity" },
  { id: 146, text: "I feel like I've been performing a version of myself for so long I don't know what's real.", category: "Self & Identity" },
  { id: 147, text: "How do I deal with shame about something from my past?", category: "Self & Identity" },
  { id: 148, text: "I'm afraid of being ordinary. Is that a healthy drive or a problem?", category: "Self & Identity" },
  { id: 149, text: "How do I stop catastrophizing when things go wrong?", category: "Self & Identity" },
  { id: 150, text: "I've never thought of myself as creative but I want to be. Is it too late?", category: "Self & Identity" },
  { id: 151, text: "How do I forgive myself for something I genuinely regret?", category: "Self & Identity" },
  { id: 152, text: "I feel like I'm always either all-in or completely checked out. How do I find balance?", category: "Self & Identity" },
  { id: 153, text: "How do I rebuild my sense of self after a breakup or major loss?", category: "Self & Identity" },
  { id: 154, text: "I have intrusive thoughts that scare me. What do I do with them?", category: "Self & Identity" },
  { id: 155, text: "How do I stop trying to control things I can't control?", category: "Self & Identity" },
  { id: 156, text: "I feel ashamed of where I am at this stage of my life. How do I move past it?", category: "Self & Identity" },
  { id: 157, text: "How do I build emotional resilience so setbacks don't wreck me?", category: "Self & Identity" },
  { id: 158, text: "I'm so focused on the future that I never enjoy the present. How do I change that?", category: "Self & Identity" },
  { id: 159, text: "How do I stop living reactively and start living intentionally?", category: "Self & Identity" },
  { id: 160, text: "I've been described as \"too sensitive.\" Is that a flaw or a feature?", category: "Self & Identity" },
  { id: 161, text: "How do I stop carrying other people's pain as my own?", category: "Self & Identity" },
  { id: 162, text: "I feel like I need permission to want what I want. Who do I ask?", category: "Self & Identity" },
  { id: 163, text: "How do I get comfortable with uncertainty?", category: "Self & Identity" },
  { id: 164, text: "I know my inner critic is lying but I believe it anyway. How do I change that?", category: "Self & Identity" },
  { id: 165, text: "How do I build a daily practice that actually connects me to myself?", category: "Self & Identity" },
  { id: 166, text: "I've numbed out for years. How do I start feeling again?", category: "Self & Identity" },
  { id: 167, text: "I feel like I missed the instruction manual for life. What do I do?", category: "Self & Identity" },
  { id: 168, text: "How do I stop waiting to feel ready before I do the things I want to do?", category: "Self & Identity" },
  { id: 169, text: "I have values I believe in but don't live by. How do I close that gap?", category: "Self & Identity" },
  { id: 170, text: "How do I become someone I actually respect?", category: "Self & Identity" },

  // HABITS, GROWTH & DISCIPLINE (40)
  { id: 171, text: "I know what to do to be healthier. I just don't do it. What's really going on?", category: "Habits, Growth & Discipline" },
  { id: 172, text: "How do I stop starting over from scratch every Monday?", category: "Habits, Growth & Discipline" },
  { id: 173, text: "I've tried journaling a dozen times and it never sticks. Why?", category: "Habits, Growth & Discipline" },
  { id: 174, text: "How do I find time for myself when I'm genuinely that busy?", category: "Habits, Growth & Discipline" },
  { id: 175, text: "I want to read more but I can't seem to finish books anymore. What happened?", category: "Habits, Growth & Discipline" },
  { id: 176, text: "How do I build a morning routine I actually want to do?", category: "Habits, Growth & Discipline" },
  { id: 177, text: "I exercise for a few weeks and then fall off completely. How do I stop this cycle?", category: "Habits, Growth & Discipline" },
  { id: 178, text: "How do I get better at following through on things I commit to?", category: "Habits, Growth & Discipline" },
  { id: 179, text: "I feel like my life is run by my to-do list. How do I change that?", category: "Habits, Growth & Discipline" },
  { id: 180, text: "How do I make a decision and actually commit to it instead of second-guessing?", category: "Habits, Growth & Discipline" },
  { id: 181, text: "I spend more time planning to change than actually changing. How do I break that?", category: "Habits, Growth & Discipline" },
  { id: 182, text: "How do I stay consistent without being rigid?", category: "Habits, Growth & Discipline" },
  { id: 183, text: "I have a goal I've had for five years and haven't started. What's the real reason?", category: "Habits, Growth & Discipline" },
  { id: 184, text: "How do I stop letting perfect be the enemy of done?", category: "Habits, Growth & Discipline" },
  { id: 185, text: "I'm a night owl who wants to be a morning person. Is that even possible?", category: "Habits, Growth & Discipline" },
  { id: 186, text: "How do I take better care of my health without making it a full-time job?", category: "Habits, Growth & Discipline" },
  { id: 187, text: "I want to learn a new skill but I feel embarrassed being a beginner. How do I get over it?", category: "Habits, Growth & Discipline" },
  { id: 188, text: "How do I build discipline around something I genuinely hate doing?", category: "Habits, Growth & Discipline" },
  { id: 189, text: "I've lost my curiosity. How do I get it back?", category: "Habits, Growth & Discipline" },
  { id: 190, text: "How do I measure growth in areas that aren't measurable?", category: "Habits, Growth & Discipline" },
  { id: 191, text: "I'm addicted to my phone and I know it. Where do I start?", category: "Habits, Growth & Discipline" },
  { id: 192, text: "How do I maintain progress when life gets hard and routine breaks down?", category: "Habits, Growth & Discipline" },
  { id: 193, text: "I want to be more intentional about how I spend my time. Where do I start?", category: "Habits, Growth & Discipline" },
  { id: 194, text: "How do I stop procrastinating on the things that matter most to me?", category: "Habits, Growth & Discipline" },
  { id: 195, text: "I sleep terribly and it affects everything. What can I actually do about it?", category: "Habits, Growth & Discipline" },
  { id: 196, text: "How do I break a habit I've had for decades?", category: "Habits, Growth & Discipline" },
  { id: 197, text: "I have too many interests and I can't focus on any of them. What do I do?", category: "Habits, Growth & Discipline" },
  { id: 198, text: "How do I stop consuming content and start creating something?", category: "Habits, Growth & Discipline" },
  { id: 199, text: "I keep abandoning projects right before they're finished. Why?", category: "Habits, Growth & Discipline" },
  { id: 200, text: "How do I build focus in a world designed to distract me?", category: "Habits, Growth & Discipline" },
  { id: 201, text: "I want to be more disciplined without becoming someone who has no fun.", category: "Habits, Growth & Discipline" },
  { id: 202, text: "How do I celebrate progress without losing momentum?", category: "Habits, Growth & Discipline" },
  { id: 203, text: "I've gained weight I want to lose, but I've tried so many times. What's different now?", category: "Habits, Growth & Discipline" },
  { id: 204, text: "How do I stop treating self-care as a reward and start treating it as a baseline?", category: "Habits, Growth & Discipline" },
  { id: 205, text: "I don't know how to rest without feeling guilty. How do I unlearn that?", category: "Habits, Growth & Discipline" },
  { id: 206, text: "How do I deal with a slump that's lasted longer than it should?", category: "Habits, Growth & Discipline" },
  { id: 207, text: "I want to volunteer or give back but I never make it a priority. What would help?", category: "Habits, Growth & Discipline" },
  { id: 208, text: "How do I build a life that looks less like survival and more like living?", category: "Habits, Growth & Discipline" },
  { id: 209, text: "I know my bad habits are coping mechanisms. So how do I actually let them go?", category: "Habits, Growth & Discipline" },
  { id: 210, text: "How do I stay committed to long-term goals when short-term rewards keep pulling me?", category: "Habits, Growth & Discipline" },

  // MONEY & SECURITY (30)
  { id: 211, text: "I feel anxious about money even when I have enough. What's that about?", category: "Money & Security" },
  { id: 212, text: "How do I have an honest conversation about money with my partner?", category: "Money & Security" },
  { id: 213, text: "I spend money when I'm stressed. How do I break this pattern?", category: "Money & Security" },
  { id: 214, text: "I have debt I'm ashamed of. Where do I start?", category: "Money & Security" },
  { id: 215, text: "How do I build a financial safety net when I'm living paycheck to paycheck?", category: "Money & Security" },
  { id: 216, text: "I've never invested and I don't know where to start without feeling stupid.", category: "Money & Security" },
  { id: 217, text: "How do I stop letting money be a source of shame?", category: "Money & Security" },
  { id: 218, text: "I grew up poor and now that I'm not, I still live like I am. Why can't I let go of that?", category: "Money & Security" },
  { id: 219, text: "My partner and I have very different spending habits. How do we get on the same page?", category: "Money & Security" },
  { id: 220, text: "How do I talk to my aging parents about their finances?", category: "Money & Security" },
  { id: 221, text: "I want to be generous but I'm afraid there won't be enough for me. How do I balance that?", category: "Money & Security" },
  { id: 222, text: "How do I make a major financial decision when the right answer isn't clear?", category: "Money & Security" },
  { id: 223, text: "I feel like money controls me more than I control it. How do I change that?", category: "Money & Security" },
  { id: 224, text: "I've been living beyond my means for years. How do I start being honest with myself?", category: "Money & Security" },
  { id: 225, text: "How do I build a healthy relationship with money when my family modeled the opposite?", category: "Money & Security" },
  { id: 226, text: "I just came into unexpected money and I don't want to blow it. What do I do?", category: "Money & Security" },
  { id: 227, text: "I'm afraid to look at my finances because I know it's bad. How do I get started?", category: "Money & Security" },
  { id: 228, text: "How do I stop feeling guilty for having more than the people I grew up with?", category: "Money & Security" },
  { id: 229, text: "My financial situation is fine but I feel like a failure. What's going on?", category: "Money & Security" },
  { id: 230, text: "How do I teach my kids about money when I don't have it figured out myself?", category: "Money & Security" },
  { id: 231, text: "I'm saving for something big but it feels impossible. How do I stay motivated?", category: "Money & Security" },
  { id: 232, text: "How do I negotiate something without feeling like I'm being greedy?", category: "Money & Security" },
  { id: 233, text: "I feel like I'll never be able to retire. How do I live with that uncertainty?", category: "Money & Security" },
  { id: 234, text: "I lent money to a friend and it changed things. How do I handle this?", category: "Money & Security" },
  { id: 235, text: "How do I stop equating my net worth with my self-worth?", category: "Money & Security" },
  { id: 236, text: "I've been financially dependent on someone and need to change that. Where do I start?", category: "Money & Security" },
  { id: 237, text: "I have a financial windfall and everyone wants something. How do I protect myself?", category: "Money & Security" },
  { id: 238, text: "How do I find the discipline to save when spending feels so much better?", category: "Money & Security" },
  { id: 239, text: "I work hard and still can't get ahead. Is this a math problem or a mindset problem?", category: "Money & Security" },
  { id: 240, text: "How do I stop being afraid to look at my bank account?", category: "Money & Security" },

  // LOSS, GRIEF & HARD TIMES (30)
  { id: 241, text: "I lost someone I love and I don't know how to function. What do I do?", category: "Loss, Grief & Hard Times" },
  { id: 242, text: "How do I grieve something that wasn't a death — a relationship, a dream, a version of my life?", category: "Loss, Grief & Hard Times" },
  { id: 243, text: "I've been through something traumatic and I can't stop replaying it. What do I do?", category: "Loss, Grief & Hard Times" },
  { id: 244, text: "How do I support myself when I'm going through something I can't talk about?", category: "Loss, Grief & Hard Times" },
  { id: 245, text: "I feel numb and I don't know if that's grief or depression. What's the difference?", category: "Loss, Grief & Hard Times" },
  { id: 246, text: "I'm going through a divorce and I don't know who I am on the other side of this.", category: "Loss, Grief & Hard Times" },
  { id: 247, text: "How do I find hope when everything around me feels dark?", category: "Loss, Grief & Hard Times" },
  { id: 248, text: "I've had a run of bad luck and I'm starting to wonder if I'm the problem.", category: "Loss, Grief & Hard Times" },
  { id: 249, text: "A friend group turned on me and it was traumatic. How do I process this?", category: "Loss, Grief & Hard Times" },
  { id: 250, text: "How do I stay functional at work when my personal life is falling apart?", category: "Loss, Grief & Hard Times" },
  { id: 251, text: "I've been in pain for so long I've forgotten what normal feels like.", category: "Loss, Grief & Hard Times" },
  { id: 252, text: "Someone I loved chose someone else. How do I make sense of that?", category: "Loss, Grief & Hard Times" },
  { id: 253, text: "I was fired from a job I loved and it destroyed my confidence. How do I come back?", category: "Loss, Grief & Hard Times" },
  { id: 254, text: "How do I find meaning after I've lost something that gave my life structure?", category: "Loss, Grief & Hard Times" },
  { id: 255, text: "I feel like I missed out on something I can never get back. How do I live with that?", category: "Loss, Grief & Hard Times" },
  { id: 256, text: "I'm caring for a sick family member and I'm disappearing. How do I survive this?", category: "Loss, Grief & Hard Times" },
  { id: 257, text: "How do I talk to my kids about something devastating that happened?", category: "Loss, Grief & Hard Times" },
  { id: 258, text: "My marriage ended and I thought it would last forever. How do I trust again?", category: "Loss, Grief & Hard Times" },
  { id: 259, text: "I'm experiencing something that no one in my life understands. How do I cope?", category: "Loss, Grief & Hard Times" },
  { id: 260, text: "I suffered a miscarriage and I don't know how to talk about it.", category: "Loss, Grief & Hard Times" },
  { id: 261, text: "How do I deal with a diagnosis that changes everything?", category: "Loss, Grief & Hard Times" },
  { id: 262, text: "I've lost my faith. I don't know what I believe anymore.", category: "Loss, Grief & Hard Times" },
  { id: 263, text: "How do I find my footing after a period of my life that broke something in me?", category: "Loss, Grief & Hard Times" },
  { id: 264, text: "I feel guilty for surviving something that hurt someone else.", category: "Loss, Grief & Hard Times" },
  { id: 265, text: "How do I find joy again after a season of real suffering?", category: "Loss, Grief & Hard Times" },
  { id: 266, text: "I've been grieving quietly for years and I don't know how to stop hiding it.", category: "Loss, Grief & Hard Times" },
  { id: 267, text: "I feel angry about what happened to me. Is that okay?", category: "Loss, Grief & Hard Times" },
  { id: 268, text: "How do I grieve a parent I had a complicated relationship with?", category: "Loss, Grief & Hard Times" },
  { id: 269, text: "I've rebuilt myself after a hard time, but I'm still afraid it'll fall apart again.", category: "Loss, Grief & Hard Times" },
  { id: 270, text: "How do I honor someone I've lost while still moving forward?", category: "Loss, Grief & Hard Times" },

  // FAITH, MEANING & BIG QUESTIONS (35)
  { id: 271, text: "What is the point of all this? I genuinely don't know and it scares me.", category: "Faith, Meaning & Big Questions" },
  { id: 272, text: "How do I find purpose when I'm just trying to get through the day?", category: "Faith, Meaning & Big Questions" },
  { id: 273, text: "I grew up religious and left the faith. I still feel the loss. What do I do with that?", category: "Faith, Meaning & Big Questions" },
  { id: 274, text: "How do I build a personal code for living when I don't have a religion?", category: "Faith, Meaning & Big Questions" },
  { id: 275, text: "I want to live for something bigger than myself. How do I find what that is?", category: "Faith, Meaning & Big Questions" },
  { id: 276, text: "How do I deal with injustice in the world without becoming bitter or numb?", category: "Faith, Meaning & Big Questions" },
  { id: 277, text: "I believe in God but my prayers feel empty. What does that mean?", category: "Faith, Meaning & Big Questions" },
  { id: 278, text: "How do I practice gratitude when I'm genuinely struggling?", category: "Faith, Meaning & Big Questions" },
  { id: 279, text: "I want to be a better person. What does that even mean?", category: "Faith, Meaning & Big Questions" },
  { id: 280, text: "How do I make peace with my own mortality?", category: "Faith, Meaning & Big Questions" },
  { id: 281, text: "I've done things I'm deeply ashamed of. Is redemption actually real?", category: "Faith, Meaning & Big Questions" },
  { id: 282, text: "How do I hold onto hope when the evidence seems against it?", category: "Faith, Meaning & Big Questions" },
  { id: 283, text: "I feel spiritually empty and I don't know how to fill that.", category: "Faith, Meaning & Big Questions" },
  { id: 284, text: "How do I define my own values without just inheriting my parents'?", category: "Faith, Meaning & Big Questions" },
  { id: 285, text: "I want to live with more integrity but I don't always know what that looks like in practice.", category: "Faith, Meaning & Big Questions" },
  { id: 286, text: "How do I make sense of suffering when it seems completely senseless?", category: "Faith, Meaning & Big Questions" },
  { id: 287, text: "I feel called to something but I don't know what it is. How do I find out?", category: "Faith, Meaning & Big Questions" },
  { id: 288, text: "What does it mean to live a good life? I'm asking seriously.", category: "Faith, Meaning & Big Questions" },
  { id: 289, text: "How do I become more compassionate, including toward myself?", category: "Faith, Meaning & Big Questions" },
  { id: 290, text: "I'm afraid of dying. Is that something I need to work through?", category: "Faith, Meaning & Big Questions" },
  { id: 291, text: "How do I live with questions I can't answer?", category: "Faith, Meaning & Big Questions" },
  { id: 292, text: "How do I know what I actually believe versus what I was told to believe?", category: "Faith, Meaning & Big Questions" },
  { id: 293, text: "I want to do more good in the world. Where do I start?", category: "Faith, Meaning & Big Questions" },
  { id: 294, text: "I feel disconnected from something sacred. How do I find my way back?", category: "Faith, Meaning & Big Questions" },
  { id: 295, text: "How do I build a ritual or practice that gives my life structure and meaning?", category: "Faith, Meaning & Big Questions" },
  { id: 296, text: "I've started thinking about legacy. What do I actually want to leave behind?", category: "Faith, Meaning & Big Questions" },
  { id: 297, text: "How do I hold my convictions without becoming rigid or self-righteous?", category: "Faith, Meaning & Big Questions" },
  { id: 298, text: "I used to feel wonder about life and now I don't. How do I get that back?", category: "Faith, Meaning & Big Questions" },
  { id: 299, text: "I'm struggling to forgive someone who hasn't asked for it. What's the path forward?", category: "Faith, Meaning & Big Questions" },
  { id: 300, text: "How do I live with more intention and less drift?", category: "Faith, Meaning & Big Questions" },
  { id: 301, text: "I feel like I've wasted years. How do I make peace with that?", category: "Faith, Meaning & Big Questions" },
  { id: 302, text: "How do I stay grounded in what matters when the world keeps demanding my attention?", category: "Faith, Meaning & Big Questions" },
  { id: 303, text: "I want to be more generous but I don't always feel it. How do I cultivate that?", category: "Faith, Meaning & Big Questions" },
  { id: 304, text: "How do I practice forgiveness as a discipline, not just a feeling?", category: "Faith, Meaning & Big Questions" },
  { id: 305, text: "How do I find beauty in ordinary life?", category: "Faith, Meaning & Big Questions" },

  // ANXIETY, MENTAL HEALTH & WELLBEING (35)
  { id: 306, text: "I feel anxious almost all the time and I don't know what I'm actually afraid of.", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 307, text: "How do I calm down in the middle of a panic attack?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 308, text: "I've been told I have high-functioning anxiety. What does that mean for how I live?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 309, text: "How do I stop my thoughts from racing when I'm trying to sleep?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 310, text: "I feel emotionally exhausted in a way that rest doesn't fix. What's wrong?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 311, text: "How do I know if I should see a therapist or if I can work through this on my own?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 312, text: "I've been on and off antidepressants for years. How do I think about this clearly?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 313, text: "I feel fine on paper but hollow inside. What is that?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 314, text: "How do I manage anger that comes out in ways I regret?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 315, text: "I've been told I'm emotionally unavailable. What does that actually mean?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 316, text: "How do I stop catastrophizing in relationships?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 317, text: "I feel like I can't afford therapy but I know I need help. What are my options?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 318, text: "How do I support someone who is struggling mentally without taking it on myself?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 319, text: "I've experienced burnout and I'm afraid it's coming back. How do I protect myself?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 320, text: "How do I process emotions instead of just suppressing them?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 321, text: "I feel disconnected from my body. How do I come back to it?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 322, text: "I have a drinking habit I'm not proud of. How do I be honest with myself about it?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 323, text: "How do I break a cycle of negative thinking that starts before I'm even awake?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 324, text: "I tend to absorb other people's emotions. How do I protect myself without shutting down?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 325, text: "I freeze up when I'm under pressure. How do I function better in high-stress moments?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 326, text: "I've been in survival mode for so long I don't know how to feel safe. What do I do?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 327, text: "How do I set better expectations for myself so I'm not constantly disappointed?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 328, text: "I feel like everyone else has it together and I don't. Is that true?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 329, text: "How do I stop seeking reassurance from everyone around me?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 330, text: "I'm dealing with something heavy alone because I don't want to be a burden.", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 331, text: "How do I know if what I'm feeling is grief, depression, or both?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 332, text: "How do I take care of my mental health without making it my whole identity?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 333, text: "I've been having really dark thoughts. How do I get help?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 334, text: "I feel like I overreact to things but I can't seem to stop. What's going on?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 335, text: "How do I find a therapist I actually connect with?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 336, text: "I've been told I have abandonment issues. What do I do with that?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 337, text: "How do I manage anxiety about things I genuinely cannot control?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 338, text: "I'm afraid that if I feel this bad now, it'll always be this bad. What do I do?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 339, text: "How do I build emotional stability when my life feels chaotic?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 340, text: "I feel like I'm white-knuckling through life. How do I actually let go?", category: "Anxiety, Mental Health & Wellbeing" },

  // PARENTING & FAMILY (25)
  { id: 341, text: "I love my kids but I've lost myself in parenthood. How do I get back?", category: "Parenting & Family" },
  { id: 342, text: "How do I parent a child who is struggling when I'm struggling too?", category: "Parenting & Family" },
  { id: 343, text: "I grew up in a dysfunctional family and I'm terrified of repeating the patterns.", category: "Parenting & Family" },
  { id: 344, text: "My child told me something that broke my heart. How do I respond without falling apart?", category: "Parenting & Family" },
  { id: 345, text: "How do I talk to my kids about money without passing on my anxiety?", category: "Parenting & Family" },
  { id: 346, text: "I feel like a failure as a parent even though I'm doing my best. How do I get out of this?", category: "Parenting & Family" },
  { id: 347, text: "My kids are growing up and I don't know who I am when they don't need me anymore.", category: "Parenting & Family" },
  { id: 348, text: "How do I discipline my child without damaging their spirit?", category: "Parenting & Family" },
  { id: 349, text: "I'm co-parenting with someone I can't stand. How do I make peace with that?", category: "Parenting & Family" },
  { id: 350, text: "How do I repair the relationship with an adult child I've hurt?", category: "Parenting & Family" },
  { id: 351, text: "I want to be a better parent than I had. Where do I even start?", category: "Parenting & Family" },
  { id: 352, text: "How do I handle a difficult in-law relationship that's hurting my marriage?", category: "Parenting & Family" },
  { id: 353, text: "I feel guilty for the things I couldn't give my children. How do I work through that?", category: "Parenting & Family" },
  { id: 354, text: "My family has a secret I've been keeping for years. What do I do with it?", category: "Parenting & Family" },
  { id: 355, text: "How do I raise kids with values in a world that pushes against them?", category: "Parenting & Family" },
  { id: 356, text: "I'm struggling as a single parent and I feel completely alone. What helps?", category: "Parenting & Family" },
  { id: 357, text: "How do I stop yelling at my kids when I'm overwhelmed?", category: "Parenting & Family" },
  { id: 358, text: "My child is struggling in ways I don't understand. How do I help?", category: "Parenting & Family" },
  { id: 359, text: "I didn't have a present parent and I grieve that as an adult. Is that normal?", category: "Parenting & Family" },
  { id: 360, text: "How do I set appropriate limits with my adult children?", category: "Parenting & Family" },
  { id: 361, text: "I want to talk to my kids about faith but I'm not sure what I believe myself.", category: "Parenting & Family" },
  { id: 362, text: "How do I balance being a supportive parent with letting my kids fail and learn?", category: "Parenting & Family" },
  { id: 363, text: "I feel like my identity as a parent has swallowed every other part of me.", category: "Parenting & Family" },
  { id: 364, text: "How do I handle a child who pushes every boundary I set?", category: "Parenting & Family" },
  { id: 365, text: "I made real mistakes as a parent. Is it too late to repair things?", category: "Parenting & Family" },

  // TRANSITIONS & LIFE DECISIONS (10) — mapped to Parenting & Family for the 9-category system
  // but keeping them as a distinct semantic group via the last category slot
  { id: 366, text: "I'm about to turn a major age and I'm not where I thought I'd be.", category: "Self & Identity" },
  { id: 367, text: "I've been given an opportunity that excites and terrifies me equally. What do I do?", category: "Career & Purpose" },
  { id: 368, text: "I'm thinking about making a major move — city, country, or life. How do I decide?", category: "Self & Identity" },
  { id: 369, text: "I feel like I'm at a crossroads and every path feels like a loss. How do I choose?", category: "Faith, Meaning & Big Questions" },
  { id: 370, text: "I've been doing something for years out of obligation. When does staying become cowardice?", category: "Self & Identity" },
  { id: 371, text: "I want to reinvent myself. Is that a gift or am I running from something?", category: "Self & Identity" },
  { id: 372, text: "I just hit a milestone I worked for and I feel nothing. What does that mean?", category: "Self & Identity" },
  { id: 373, text: "How do I make a big decision when the people I love disagree with my direction?", category: "Relationships & Communication" },
  { id: 374, text: "I'm afraid that choosing one path means losing everything else. How do I get past that?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 375, text: "I've built a life that looks right from the outside but something important is missing. What do I do?", category: "Self & Identity" },

  // Extra prompts to reach 400 — spread across categories
  { id: 376, text: "How do I stop waiting for the perfect moment and just begin?", category: "Habits, Growth & Discipline" },
  { id: 377, text: "I've been betrayed by someone I trusted completely. How do I move forward?", category: "Relationships & Communication" },
  { id: 378, text: "How do I find the courage to say no to people I love?", category: "Self & Identity" },
  { id: 379, text: "I've been carrying anger for years. How do I finally put it down?", category: "Loss, Grief & Hard Times" },
  { id: 380, text: "How do I ask for help without feeling like I'm a burden?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 381, text: "I feel like I've been sleepwalking through my life. How do I wake up?", category: "Self & Identity" },
  { id: 382, text: "How do I know if I'm being too hard on myself or not hard enough?", category: "Self & Identity" },
  { id: 383, text: "I want to create something meaningful but I'm afraid it won't be good enough.", category: "Career & Purpose" },
  { id: 384, text: "How do I live with the fact that some things can't be fixed?", category: "Faith, Meaning & Big Questions" },
  { id: 385, text: "I feel like I've outgrown my old life but I don't know what the new one looks like.", category: "Self & Identity" },
  { id: 386, text: "How do I stop dwelling on the past when the past keeps showing up in my present?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 387, text: "I want to be more present for the people I love. What actually helps?", category: "Relationships & Communication" },
  { id: 388, text: "How do I deal with feeling behind everyone else my age?", category: "Self & Identity" },
  { id: 389, text: "I feel like I've been performing competence for years. When does it become real?", category: "Career & Purpose" },
  { id: 390, text: "How do I find meaning in small acts when the big picture feels overwhelming?", category: "Faith, Meaning & Big Questions" },
  { id: 391, text: "I want to take better care of my body but I keep breaking my own promises.", category: "Habits, Growth & Discipline" },
  { id: 392, text: "How do I deal with feeling unappreciated by people I work hard for?", category: "Relationships & Communication" },
  { id: 393, text: "I've lost someone who was also complicated to love. How do I grieve that honestly?", category: "Loss, Grief & Hard Times" },
  { id: 394, text: "How do I keep going when I've already failed at this before?", category: "Habits, Growth & Discipline" },
  { id: 395, text: "I want to be more honest with myself. Where do I even start?", category: "Self & Identity" },
  { id: 396, text: "How do I stop letting guilt drive my decisions?", category: "Anxiety, Mental Health & Wellbeing" },
  { id: 397, text: "I've been strong for everyone else. Who do I get to fall apart with?", category: "Relationships & Communication" },
  { id: 398, text: "How do I keep hope alive when the world feels like it's going backwards?", category: "Faith, Meaning & Big Questions" },
  { id: 399, text: "I feel like I'm always preparing for life instead of actually living it.", category: "Self & Identity" },
  { id: 400, text: "How do I honor my past without being trapped by it?", category: "Self & Identity" },
];

export const CATEGORIES: PromptCategory[] = [
  "Relationships & Communication",
  "Career & Purpose",
  "Self & Identity",
  "Habits, Growth & Discipline",
  "Money & Security",
  "Loss, Grief & Hard Times",
  "Faith, Meaning & Big Questions",
  "Anxiety, Mental Health & Wellbeing",
  "Parenting & Family",
];

/**
 * Select 5 prompts for today, one from each of 5 different categories.
 * Seeded by date so the same 5 show all day; refreshes at midnight.
 * Pure client-side — no backend needed for Path A.
 */
// Replaces the getDailyPrompts function in dailyPrompts.ts
// Drop this into the bottom of that file instead.

/**
 * Select 5 prompts for today — one from each of 5 different categories.
 * Uses day-of-year as an incrementing counter so:
 *   - All 5 prompts change every single day
 *   - No prompt repeats within a ~60 day window
 *   - Same 5 show all day; refreshes at midnight
 */
export function getDailyPrompts(): DailyPrompt[] {
  const today = new Date();
  // Day number since a fixed epoch — increments by 1 every calendar day
  const epoch = new Date(2024, 0, 1).getTime();
  const dayNumber = Math.floor((today.getTime() - epoch) / (1000 * 60 * 60 * 24));

  // Rotate which 5 of the 9 categories appear today
  // Full cycle of all 9 categories repeats every 9 days
  const categoryOrder = [...CATEGORIES];
  const catOffset = dayNumber % categoryOrder.length;
  const todayCategories: PromptCategory[] = [];
  for (let i = 0; i < 5; i++) {
    todayCategories.push(categoryOrder[(catOffset + i) % categoryOrder.length]);
  }

  // From each category, pick one prompt using dayNumber as offset
  // This advances through the pool so prompts don't repeat for many weeks
  const result: DailyPrompt[] = [];
  todayCategories.forEach((cat, idx) => {
    const pool = DAILY_PROMPTS.filter((p) => p.category === cat);
    // Each category uses a different stride to avoid clustering
    const stride = dayNumber + idx * 37;
    const pick = pool[stride % pool.length];
    result.push(pick);
  });

  return result;
}
