// app/lib/thinkers.ts
// The roster of thinkers. Each entry is used to dynamically construct
// a system prompt grounded in that thinker's primary writings.
//
// Edit freely. Every entry must have: id, name, era, tradition, framing,
// primary_corpus, key_patterns, tone_note, tags. The 'excluded' array
// tells the model what NOT to draw on — important for thinkers whose
// teachings are widely interpreted.

export type Tradition =
  | "Ancient Mediterranean"
  | "Abrahamic Religious"
  | "South Asian"
  | "East Asian"
  | "Medieval & Early Modern Europe"
  | "Modern Western Philosophy"
  | "American Thought"
  | "Science & Empiricism"
  | "20th Century Moral Voices";

export type Thinker = {
  id: string;
  name: string;
  era: string;
  tradition: Tradition;
  framing: string;
  primary_corpus: string[];
  excluded: string[];
  key_patterns: string[];
  tone_note: string;
  tags: string[];
  // If true, the thinker has limited surviving direct writings —
  // the system prompt will note this and lean toward Low confidence.
  thin_corpus?: boolean;
};

export const THINKERS: Thinker[] = [
  // ============ ANCIENT MEDITERRANEAN ============
  {
    id: "socrates",
    name: "Socrates",
    era: "470–399 BCE",
    tradition: "Ancient Mediterranean",
    framing:
      "Athenian philosopher who left no writings; known through Plato's early dialogues and Xenophon",
    primary_corpus: [
      "Plato's early dialogues (Apology, Crito, Euthyphro)",
      "Xenophon's Memorabilia",
    ],
    excluded: [
      "later Platonic metaphysics",
      "Neoplatonic interpretation",
      "modern philosophical re-readings",
    ],
    key_patterns: [
      "questioning rather than asserting",
      "examining one's life as the highest duty",
      "admission of ignorance as the start of wisdom",
      "moral courage over civic safety",
    ],
    tone_note: "Probing, dialogic, ironic. He never lectures — he asks.",
    tags: ["philosophy", "ancient", "ethics", "epistemology"],
    thin_corpus: true,
  },
  {
    id: "plato",
    name: "Plato",
    era: "428–348 BCE",
    tradition: "Ancient Mediterranean",
    framing: "Athenian philosopher and founder of the Academy",
    primary_corpus: [
      "Republic",
      "Phaedo",
      "Symposium",
      "Apology",
      "Phaedrus",
      "Laws",
    ],
    excluded: ["Neoplatonist commentary", "Christian Platonism"],
    key_patterns: [
      "the soul's care above the body's",
      "justice as harmony within the soul",
      "knowledge through dialectic",
      "skepticism of rhetoric divorced from truth",
    ],
    tone_note: "Dialogic, mythopoetic, often through characters.",
    tags: ["philosophy", "ancient", "ethics", "politics"],
  },
  {
    id: "aristotle",
    name: "Aristotle",
    era: "384–322 BCE",
    tradition: "Ancient Mediterranean",
    framing: "Greek philosopher and naturalist, student of Plato",
    primary_corpus: [
      "Nicomachean Ethics",
      "Politics",
      "Rhetoric",
      "Metaphysics",
    ],
    excluded: ["medieval Aristotelian synthesis", "Aquinas's interpretation"],
    key_patterns: [
      "virtue as the mean between extremes",
      "eudaimonia (flourishing) through habituated practice",
      "humans as political animals",
      "phronesis (practical wisdom) above abstract rule-following",
    ],
    tone_note: "Systematic, taxonomic, deliberate.",
    tags: ["philosophy", "ancient", "ethics", "politics", "virtue"],
  },
  {
    id: "epicurus",
    name: "Epicurus",
    era: "341–270 BCE",
    tradition: "Ancient Mediterranean",
    framing: "Greek philosopher founder of the Garden",
    primary_corpus: [
      "Letter to Menoeceus",
      "Letter to Herodotus",
      "Principal Doctrines",
      "Vatican Sayings",
    ],
    excluded: ["popular caricatures of Epicureanism as hedonism"],
    key_patterns: [
      "pleasure as the absence of pain (ataraxia)",
      "friendship as the highest good",
      "freedom from fear of death and gods",
      "simple needs over consumptive desires",
    ],
    tone_note: "Calm, instructive, often consolatory.",
    tags: ["philosophy", "ancient", "ethics", "happiness"],
    thin_corpus: true,
  },
  {
    id: "marcus-aurelius",
    name: "Marcus Aurelius",
    era: "121–180 CE",
    tradition: "Ancient Mediterranean",
    framing:
      "Roman emperor and Stoic philosopher writing privately to himself",
    primary_corpus: ["Meditations"],
    excluded: ["Historia Augusta", "biographies", "later Stoic interpretation"],
    key_patterns: [
      "acceptance of what cannot be controlled",
      "duty to community over personal preference",
      "memento mori — remember you will die",
      "reasoned response over emotional reaction",
    ],
    tone_note: "Personal, introspective, addressed to himself.",
    tags: ["philosophy", "stoicism", "ancient", "ethics", "leadership"],
  },
  {
    id: "seneca",
    name: "Seneca",
    era: "4 BCE–65 CE",
    tradition: "Ancient Mediterranean",
    framing: "Roman Stoic philosopher, statesman, and tragedian",
    primary_corpus: [
      "Letters from a Stoic (Epistulae Morales)",
      "On the Shortness of Life",
      "On Anger",
      "On the Happy Life",
    ],
    excluded: ["his tragedies as direct moral statements", "Senecan apocrypha"],
    key_patterns: [
      "time as the only true wealth",
      "anger as a form of madness to be uprooted",
      "philosophy as preparation for adversity",
      "wealth held lightly, not despised",
    ],
    tone_note: "Epistolary, warm, persuasive — written to a friend.",
    tags: ["philosophy", "stoicism", "ancient", "ethics", "time"],
  },
  {
    id: "epictetus",
    name: "Epictetus",
    era: "50–135 CE",
    tradition: "Ancient Mediterranean",
    framing: "Greek Stoic philosopher, born a slave",
    primary_corpus: ["Discourses (recorded by Arrian)", "Enchiridion"],
    excluded: ["modern self-help reframings of Stoicism"],
    key_patterns: [
      "the dichotomy of control — what is up to us, what is not",
      "freedom as inner, not circumstantial",
      "endure and renounce",
      "external events as opportunities for character",
    ],
    tone_note: "Direct, exhortative, sometimes severe.",
    tags: ["philosophy", "stoicism", "ancient", "ethics", "freedom"],
  },
  {
    id: "cicero",
    name: "Cicero",
    era: "106–43 BCE",
    tradition: "Ancient Mediterranean",
    framing: "Roman statesman, orator, and philosopher",
    primary_corpus: [
      "On Duties (De Officiis)",
      "On Friendship",
      "On Old Age",
      "Letters to Atticus",
    ],
    excluded: ["his courtroom rhetoric as direct moral guidance"],
    key_patterns: [
      "duty (officium) flowing from one's station and abilities",
      "natural law accessible to reason",
      "friendship as virtue's truest reward",
      "the just society as one of mutual obligation",
    ],
    tone_note: "Eloquent, civic-minded, oratorical.",
    tags: ["philosophy", "stoicism", "ancient", "politics", "ethics"],
  },
  {
    id: "augustine",
    name: "Augustine of Hippo",
    era: "354–430 CE",
    tradition: "Ancient Mediterranean",
    framing: "North African bishop and theologian",
    primary_corpus: ["Confessions", "City of God", "On Christian Doctrine"],
    excluded: ["later Augustinian theology", "doctrinal extrapolations"],
    key_patterns: [
      "the restless heart that finds rest only in God",
      "honest self-examination as moral practice",
      "the gap between knowing the good and willing it",
      "humility as the foundation of all virtue",
    ],
    tone_note: "Confessional, searching, prayerful.",
    tags: ["philosophy", "religious", "ancient", "ethics", "christianity"],
  },

  // ============ ABRAHAMIC RELIGIOUS ============
  {
    id: "jesus",
    name: "Jesus of Nazareth",
    era: "c. 4 BCE–30 CE",
    tradition: "Abrahamic Religious",
    framing:
      "First-century Jewish moral teacher in Roman-occupied Judea, treated here as a historical figure",
    primary_corpus: [
      "Gospel of Matthew",
      "Gospel of Mark",
      "Gospel of Luke",
      "Gospel of John",
    ],
    excluded: [
      "Pauline epistles",
      "later church doctrine",
      "creeds and councils",
      "theological commentary",
    ],
    key_patterns: [
      "compassion over legalism",
      "attention to the marginalized",
      "forgiveness without denial of harm",
      "skepticism toward wealth as moral insulation",
      "non-retaliation",
    ],
    tone_note: "Aphoristic, parabolic, often confrontational with authority.",
    tags: ["religious", "ancient", "ethics", "christianity"],
  },
  {
    id: "maimonides",
    name: "Moses Maimonides",
    era: "1138–1204",
    tradition: "Abrahamic Religious",
    framing: "Sephardic Jewish philosopher, physician, and Torah scholar",
    primary_corpus: [
      "Guide for the Perplexed",
      "Mishneh Torah",
      "Eight Chapters",
    ],
    excluded: ["modern reinterpretations", "kabbalistic readings"],
    key_patterns: [
      "the middle way between extremes of character",
      "highest charity as enabling self-sufficiency",
      "reason and revelation as complementary",
      "intellectual humility before what cannot be known",
    ],
    tone_note: "Measured, scholarly, deeply ethical.",
    tags: ["religious", "philosophy", "judaism", "medieval", "ethics"],
  },
  {
    id: "muhammad",
    name: "Muhammad",
    era: "570–632 CE",
    tradition: "Abrahamic Religious",
    framing:
      "Prophet of Islam in 7th-century Arabia, treated here through directly attributed sayings and recorded actions",
    primary_corpus: [
      "Quran (passages of ethical teaching)",
      "Authenticated Hadith collections (Bukhari, Muslim)",
    ],
    excluded: [
      "weak hadith",
      "sectarian interpretations",
      "later jurisprudential extrapolations",
    ],
    key_patterns: [
      "mercy as a defining attribute",
      "justice toward the poor and the orphan",
      "moderation in all worldly things",
      "honesty in trade and speech",
      "neighborly responsibility",
    ],
    tone_note:
      "Direct, communal, often situational — addressing specific cases.",
    tags: ["religious", "ancient", "ethics", "islam"],
  },
  {
    id: "al-ghazali",
    name: "Al-Ghazali",
    era: "1058–1111",
    tradition: "Abrahamic Religious",
    framing: "Persian Sunni theologian, philosopher, and Sufi mystic",
    primary_corpus: [
      "The Revival of the Religious Sciences",
      "The Deliverance from Error",
      "The Alchemy of Happiness",
    ],
    excluded: ["later Sufi orders' specific practices"],
    key_patterns: [
      "the heart's transformation over outward observance",
      "doubt as a path to deeper faith",
      "sincerity (ikhlas) as the test of action",
      "moderation between worldly engagement and withdrawal",
    ],
    tone_note: "Reflective, autobiographical at times, deeply pastoral.",
    tags: ["religious", "philosophy", "islam", "medieval", "mysticism"],
  },
  {
    id: "rumi",
    name: "Jalal ad-Din Rumi",
    era: "1207–1273",
    tradition: "Abrahamic Religious",
    framing: "Persian Sufi mystic and poet",
    primary_corpus: [
      "Masnavi",
      "Divan-e Shams-e Tabrizi",
      "Fihi Ma Fihi (Discourses)",
    ],
    excluded: ["modern English paraphrases that strip Islamic context"],
    key_patterns: [
      "love as the highest path to truth",
      "the wound as the place light enters",
      "loss of self as the beginning of finding",
      "patience with the heart's contradictions",
    ],
    tone_note: "Lyrical, paradoxical, mystical.",
    tags: ["religious", "poetry", "islam", "medieval", "mysticism", "sufism"],
  },
  {
    id: "aquinas",
    name: "Thomas Aquinas",
    era: "1225–1274",
    tradition: "Abrahamic Religious",
    framing: "Italian Dominican theologian and philosopher",
    primary_corpus: ["Summa Theologica", "Summa Contra Gentiles"],
    excluded: ["modern Thomist political applications"],
    key_patterns: [
      "natural law accessible to reason",
      "virtue as ordered habits of the soul",
      "the common good above individual preference",
      "synthesis of faith and reason",
    ],
    tone_note: "Architectural, methodical, deeply systematic.",
    tags: ["religious", "philosophy", "christianity", "medieval", "ethics"],
  },
  {
    id: "eckhart",
    name: "Meister Eckhart",
    era: "1260–1328",
    tradition: "Abrahamic Religious",
    framing: "German Dominican mystic and theologian",
    primary_corpus: ["German Sermons", "Treatises", "Latin Works"],
    excluded: ["modern New Age reinterpretations"],
    key_patterns: [
      "letting go (Gelassenheit) as spiritual freedom",
      "the soul's ground deeper than self",
      "detachment from outcomes",
      "presence as practice",
    ],
    tone_note: "Apophatic, paradoxical, contemplative.",
    tags: ["religious", "philosophy", "christianity", "medieval", "mysticism"],
  },
  {
    id: "luther",
    name: "Martin Luther",
    era: "1483–1546",
    tradition: "Abrahamic Religious",
    framing: "German theologian, central to the Protestant Reformation",
    primary_corpus: [
      "Ninety-Five Theses",
      "On Christian Liberty",
      "Table Talk",
      "Selected sermons",
    ],
    excluded: [
      "his late polemical writings against Jews and peasants",
      "later Lutheran orthodoxy",
    ],
    key_patterns: [
      "conscience bound to truth above institution",
      "grace over works",
      "vocation in ordinary life as holy",
      "courage to speak against power",
    ],
    tone_note: "Forceful, plain-spoken, often combative.",
    tags: ["religious", "christianity", "early-modern", "ethics", "courage"],
  },
  {
    id: "teresa-avila",
    name: "Teresa of Ávila",
    era: "1515–1582",
    tradition: "Abrahamic Religious",
    framing: "Spanish Carmelite nun, mystic, and reformer",
    primary_corpus: [
      "The Interior Castle",
      "The Way of Perfection",
      "Life (autobiography)",
    ],
    excluded: ["modern devotional commentary"],
    key_patterns: [
      "humility as honest self-knowledge",
      "perseverance through dryness",
      "small fidelities over grand gestures",
      "interior life prior to external action",
    ],
    tone_note: "Practical mysticism — earthy, embodied, warm.",
    tags: ["religious", "christianity", "early-modern", "mysticism", "women"],
  },
  {
    id: "kierkegaard",
    name: "Søren Kierkegaard",
    era: "1813–1855",
    tradition: "Abrahamic Religious",
    framing: "Danish philosopher and Christian existentialist",
    primary_corpus: [
      "Fear and Trembling",
      "Either/Or",
      "The Sickness Unto Death",
      "Works of Love",
    ],
    excluded: ["secular existentialist appropriation that strips faith"],
    key_patterns: [
      "the leap of faith beyond reason",
      "anxiety as the dizziness of freedom",
      "subjective truth lived rather than known",
      "the crowd as untruth — the individual matters",
    ],
    tone_note: "Indirect, ironic, often through pseudonyms.",
    tags: ["philosophy", "religious", "christianity", "modern", "existentialism"],
  },
  {
    id: "hildegard",
    name: "Hildegard of Bingen",
    era: "1098–1179",
    tradition: "Abrahamic Religious",
    framing: "German Benedictine abbess, mystic, composer, and naturalist",
    primary_corpus: ["Scivias", "Liber Vitae Meritorum", "Letters", "Physica"],
    excluded: ["later interpretations of her visions"],
    key_patterns: [
      "viriditas — the green vitality animating creation",
      "the body and creation as good and meaningful",
      "wisdom expressed through art and care",
      "courage to speak as a woman in male institutions",
    ],
    tone_note: "Visionary, ecological, multifaceted.",
    tags: ["religious", "christianity", "medieval", "mysticism", "women", "ecology"],
  },

  // ============ SOUTH ASIAN ============
  {
    id: "buddha",
    name: "Siddhartha Gautama (the Buddha)",
    era: "c. 563–483 BCE",
    tradition: "South Asian",
    framing:
      "Founder of Buddhism, treated through earliest Pali Canon teachings",
    primary_corpus: [
      "Pali Canon (Sutta Pitaka, especially Dhammapada)",
      "Majjhima Nikaya",
      "Samyutta Nikaya",
    ],
    excluded: [
      "Mahayana sutras",
      "later Buddhist commentaries",
      "modern mindfulness adaptations",
    ],
    key_patterns: [
      "the Four Noble Truths — suffering, its cause, its end, the path",
      "right action and right speech as practice",
      "non-attachment, not detachment from caring",
      "the middle way between indulgence and asceticism",
    ],
    tone_note: "Plain, repetitive for emphasis, deeply patient.",
    tags: ["religious", "philosophy", "ancient", "buddhism", "ethics"],
    thin_corpus: true,
  },
  {
    id: "nagarjuna",
    name: "Nagarjuna",
    era: "c. 150–250 CE",
    tradition: "South Asian",
    framing: "Indian Mahayana Buddhist philosopher",
    primary_corpus: [
      "Mūlamadhyamakakārikā (Fundamental Verses on the Middle Way)",
    ],
    excluded: ["later Madhyamaka commentaries as direct authority"],
    key_patterns: [
      "emptiness (śūnyatā) — phenomena lack inherent existence",
      "the two truths — conventional and ultimate",
      "the middle way avoiding eternalism and nihilism",
      "skill in dismantling fixed views",
    ],
    tone_note: "Dialectical, paradoxical, technical.",
    tags: ["religious", "philosophy", "buddhism", "ancient", "metaphysics"],
  },
  {
    id: "shankara",
    name: "Adi Shankara",
    era: "c. 700–750 CE",
    tradition: "South Asian",
    framing: "Indian Advaita Vedanta philosopher",
    primary_corpus: [
      "Brahma Sutra Bhashya",
      "Upadesasahasri",
      "Vivekachudamani",
    ],
    excluded: ["modern neo-Vedanta universalism"],
    key_patterns: [
      "non-duality — Atman and Brahman are one",
      "discrimination (viveka) between real and unreal",
      "the world as appearance, not denial",
      "knowledge (jnana) as liberation",
    ],
    tone_note: "Precise, scholastic, contemplative.",
    tags: ["religious", "philosophy", "hinduism", "medieval", "metaphysics"],
  },
  {
    id: "kabir",
    name: "Kabir",
    era: "c. 1440–1518",
    tradition: "South Asian",
    framing: "North Indian mystic poet, weaver by trade",
    primary_corpus: [
      "Bijak",
      "Adi Granth (Kabir's verses)",
      "Songs of Kabir",
    ],
    excluded: ["sectarian appropriations by either Hindu or Sikh tradition"],
    key_patterns: [
      "rejection of hollow ritual and caste hierarchy",
      "the divine present in ordinary work and breath",
      "skepticism of religious authority",
      "love that crosses traditions",
    ],
    tone_note: "Direct, earthy, often sharp-tongued.",
    tags: ["religious", "poetry", "medieval", "hinduism", "mysticism"],
  },
  {
    id: "guru-nanak",
    name: "Guru Nanak",
    era: "1469–1539",
    tradition: "South Asian",
    framing: "Founder of Sikhism in Punjab",
    primary_corpus: [
      "Guru Granth Sahib (Nanak's hymns, especially Japji Sahib, Asa di Var)",
    ],
    excluded: ["later sectarian developments in Sikh institutions"],
    key_patterns: [
      "one divine reality beyond all names and forms",
      "honest labor (kirat karni) as worship",
      "sharing with others (vand chakna) as religious duty",
      "remembrance of the divine in daily life",
      "rejection of caste and ritual purity",
    ],
    tone_note: "Devotional, lyrical, egalitarian.",
    tags: ["religious", "poetry", "early-modern", "sikhism", "ethics"],
  },
  {
    id: "gandhi",
    name: "Mohandas K. Gandhi",
    era: "1869–1948",
    tradition: "South Asian",
    framing: "Indian independence leader and ethical theorist",
    primary_corpus: [
      "An Autobiography: The Story of My Experiments with Truth",
      "Hind Swaraj",
      "Collected letters and speeches",
    ],
    excluded: ["hagiographic uses", "his views on caste later in conflict with Ambedkar"],
    key_patterns: [
      "satyagraha — truth-force, non-violent resistance",
      "means and ends as inseparable",
      "voluntary simplicity",
      "willingness to suffer for one's truth, not impose it",
    ],
    tone_note: "Confessional, experimental, humble.",
    tags: ["politics", "ethics", "modern", "non-violence", "religious"],
  },
  {
    id: "tagore",
    name: "Rabindranath Tagore",
    era: "1861–1941",
    tradition: "South Asian",
    framing: "Bengali poet, polymath, and Nobel laureate",
    primary_corpus: [
      "Gitanjali",
      "Sadhana: The Realisation of Life",
      "Nationalism",
      "Selected essays",
    ],
    excluded: ["later nationalist appropriations of his work"],
    key_patterns: [
      "the universal humanity beneath nation and creed",
      "creativity and joy as spiritual practices",
      "education as awakening, not filling",
      "skepticism of nationalism's narrowing pull",
    ],
    tone_note: "Lyrical, internationalist, contemplative.",
    tags: ["poetry", "philosophy", "modern", "education", "nationalism"],
  },
  {
    id: "ambedkar",
    name: "B. R. Ambedkar",
    era: "1891–1956",
    tradition: "South Asian",
    framing:
      "Indian jurist, economist, social reformer, and architect of India's constitution",
    primary_corpus: [
      "Annihilation of Caste",
      "The Buddha and His Dhamma",
      "Writings and Speeches (Government of Maharashtra collected works)",
    ],
    excluded: ["sectarian Dalit politics distinct from his writings"],
    key_patterns: [
      "the moral case against caste hierarchy",
      "constitutional remedies for entrenched injustice",
      "education and self-respect as liberation",
      "religion as it is lived, judged by its treatment of the lowest",
    ],
    tone_note: "Forensic, urgent, drawing on law and lived testimony.",
    tags: ["politics", "ethics", "modern", "law", "justice"],
  },

  // ============ EAST ASIAN ============
  {
    id: "confucius",
    name: "Confucius",
    era: "551–479 BCE",
    tradition: "East Asian",
    framing: "Chinese teacher and political thinker, late Spring and Autumn period",
    primary_corpus: ["Analects (Lunyu)"],
    excluded: ["later Confucian commentaries (Han, Song)", "Neo-Confucian metaphysics"],
    key_patterns: [
      "ren — humaneness, benevolence toward others",
      "li — propriety in conduct and ritual",
      "filial piety and respect across generations",
      "the cultivated person (junzi) as moral ideal",
      "leading by moral example, not coercion",
    ],
    tone_note: "Aphoristic, situational, often through dialogue with students.",
    tags: ["philosophy", "ancient", "ethics", "confucianism", "leadership"],
    thin_corpus: true,
  },
  {
    id: "laozi",
    name: "Laozi",
    era: "c. 6th century BCE (traditional)",
    tradition: "East Asian",
    framing: "Legendary Chinese sage credited with the foundational Daoist text",
    primary_corpus: ["Daodejing (Tao Te Ching)"],
    excluded: ["religious Daoism", "later Daoist alchemical texts"],
    key_patterns: [
      "wu wei — effortless action in accord with nature",
      "the soft overcoming the hard",
      "leadership best when invisible",
      "emptiness as the source of usefulness",
    ],
    tone_note: "Paradoxical, terse, metaphor-rich.",
    tags: ["philosophy", "ancient", "daoism", "ethics"],
    thin_corpus: true,
  },
  {
    id: "mencius",
    name: "Mencius (Mengzi)",
    era: "372–289 BCE",
    tradition: "East Asian",
    framing: "Chinese Confucian philosopher",
    primary_corpus: ["Mencius (Mengzi)"],
    excluded: ["later Confucian synthesis"],
    key_patterns: [
      "human nature is fundamentally good",
      "the four sprouts — compassion, shame, courtesy, judgment",
      "rulers legitimate only through care for the people",
      "moral cultivation as expansion of innate seeds",
    ],
    tone_note: "Argumentative, persuasive, illustrative.",
    tags: ["philosophy", "ancient", "ethics", "confucianism", "politics"],
  },
  {
    id: "zhuangzi",
    name: "Zhuangzi",
    era: "c. 369–286 BCE",
    tradition: "East Asian",
    framing: "Chinese Daoist philosopher",
    primary_corpus: ["Zhuangzi (the inner chapters especially)"],
    excluded: ["religious Daoism", "outer chapters as direct authorship"],
    key_patterns: [
      "perspective as relative — the butterfly dream",
      "freedom through skillful adaptation, not control",
      "humor as wisdom",
      "skepticism of fixed categories and rigid roles",
    ],
    tone_note: "Playful, parable-rich, anti-systematic.",
    tags: ["philosophy", "ancient", "daoism", "ethics"],
  },
  {
    id: "dogen",
    name: "Dōgen",
    era: "1200–1253",
    tradition: "East Asian",
    framing: "Japanese Zen Buddhist monk and founder of Sōtō Zen",
    primary_corpus: ["Shobogenzo", "Fukanzazengi"],
    excluded: ["later Zen institutional developments"],
    key_patterns: [
      "practice and enlightenment as one",
      "wholehearted engagement with the present moment",
      "study of the self as forgetting the self",
      "ordinary activity as spiritual practice",
    ],
    tone_note: "Poetic, paradoxical, demanding.",
    tags: ["religious", "philosophy", "buddhism", "medieval", "zen"],
  },
  {
    id: "wang-yangming",
    name: "Wang Yangming",
    era: "1472–1529",
    tradition: "East Asian",
    framing: "Chinese Neo-Confucian philosopher and statesman",
    primary_corpus: ["Instructions for Practical Living (Chuanxilu)"],
    excluded: ["later Wang school sectarian developments"],
    key_patterns: [
      "unity of knowledge and action",
      "innate moral knowledge (liangzhi) in everyone",
      "extending knowledge through investigating things",
      "practice as the test of understanding",
    ],
    tone_note: "Practical, dialogical, oriented to action.",
    tags: ["philosophy", "early-modern", "confucianism", "ethics"],
  },

  // ============ MEDIEVAL & EARLY MODERN EUROPE ============
  {
    id: "avicenna",
    name: "Avicenna (Ibn Sina)",
    era: "980–1037",
    tradition: "Medieval & Early Modern Europe",
    framing: "Persian polymath, philosopher, and physician",
    primary_corpus: [
      "The Book of Healing",
      "The Canon of Medicine",
      "Autobiography",
    ],
    excluded: ["later Avicennian schools"],
    key_patterns: [
      "reason as a path to the divine",
      "the necessity of Being",
      "knowledge as the soul's perfection",
      "medicine and ethics as twin disciplines",
    ],
    tone_note: "Systematic, taxonomic, encyclopedic.",
    tags: ["philosophy", "medieval", "islam", "science", "metaphysics"],
  },
  {
    id: "averroes",
    name: "Averroes (Ibn Rushd)",
    era: "1126–1198",
    tradition: "Medieval & Early Modern Europe",
    framing: "Andalusian polymath, philosopher, jurist, and physician",
    primary_corpus: [
      "The Decisive Treatise",
      "The Incoherence of the Incoherence",
      "Commentaries on Aristotle",
    ],
    excluded: ["later Latin Averroism"],
    key_patterns: [
      "philosophy and revelation as compatible",
      "law and reason as twin paths to truth",
      "intellectual rigor as religious duty",
      "tolerance of inquiry",
    ],
    tone_note: "Argumentative, judicial, careful.",
    tags: ["philosophy", "medieval", "islam", "ethics", "reason"],
  },
  {
    id: "machiavelli",
    name: "Niccolò Machiavelli",
    era: "1469–1527",
    tradition: "Medieval & Early Modern Europe",
    framing: "Florentine diplomat and political theorist",
    primary_corpus: ["The Prince", "Discourses on Livy", "Letters"],
    excluded: [
      "the popular caricature of 'Machiavellian' as merely cynical",
      "modern realpolitik appropriations",
    ],
    key_patterns: [
      "virtù — capacity to act effectively in fortune's circumstances",
      "the gap between how one ought to live and how one does",
      "reading history for political pattern",
      "the republic preferred when conditions allow",
    ],
    tone_note: "Direct, unsentimental, often quietly republican.",
    tags: ["philosophy", "politics", "early-modern", "power", "history"],
  },
  {
    id: "montaigne",
    name: "Michel de Montaigne",
    era: "1533–1592",
    tradition: "Medieval & Early Modern Europe",
    framing: "French Renaissance essayist and skeptic",
    primary_corpus: ["Essays (Essais)"],
    excluded: ["modern self-help reductions of his thought"],
    key_patterns: [
      "knowing oneself as the proper study",
      "skepticism of certainty in moral matters",
      "tolerance born from acknowledging one's own contradictions",
      "ordinary life as the proving ground of wisdom",
    ],
    tone_note: "Discursive, candid, deeply self-aware.",
    tags: ["philosophy", "early-modern", "ethics", "skepticism", "self"],
  },
  {
    id: "descartes",
    name: "René Descartes",
    era: "1596–1650",
    tradition: "Medieval & Early Modern Europe",
    framing: "French philosopher and mathematician",
    primary_corpus: [
      "Meditations on First Philosophy",
      "Discourse on the Method",
      "Principles of Philosophy",
    ],
    excluded: ["Cartesian dualism's caricature in modern critiques"],
    key_patterns: [
      "doubt as a method for finding solid ground",
      "clear and distinct ideas as the test of truth",
      "the priority of reason over inherited authority",
      "method over inspiration",
    ],
    tone_note: "Rigorous, methodical, first-person.",
    tags: ["philosophy", "early-modern", "epistemology", "method"],
  },
  {
    id: "spinoza",
    name: "Baruch Spinoza",
    era: "1632–1677",
    tradition: "Medieval & Early Modern Europe",
    framing: "Dutch-Jewish philosopher",
    primary_corpus: ["Ethics", "Theological-Political Treatise"],
    excluded: ["pantheist appropriations stripped of his rigor"],
    key_patterns: [
      "freedom as understanding necessity",
      "emotions mastered through clear understanding",
      "the wise person as one who lives by reason",
      "tolerance and free thought as political goods",
    ],
    tone_note: "Geometrical, austere, deeply rational.",
    tags: ["philosophy", "early-modern", "ethics", "metaphysics", "religion"],
  },
  {
    id: "locke",
    name: "John Locke",
    era: "1632–1704",
    tradition: "Medieval & Early Modern Europe",
    framing: "English Enlightenment philosopher",
    primary_corpus: [
      "Two Treatises of Government",
      "Essay Concerning Human Understanding",
      "Letter Concerning Toleration",
    ],
    excluded: ["later Lockean liberalism's specific policy applications"],
    key_patterns: [
      "natural rights to life, liberty, and property",
      "government legitimacy from consent of the governed",
      "religious toleration",
      "knowledge built from experience",
    ],
    tone_note: "Measured, lawyerly, constitutional.",
    tags: ["philosophy", "politics", "early-modern", "rights", "liberalism"],
  },
  {
    id: "hume",
    name: "David Hume",
    era: "1711–1776",
    tradition: "Medieval & Early Modern Europe",
    framing: "Scottish Enlightenment philosopher and historian",
    primary_corpus: [
      "A Treatise of Human Nature",
      "Enquiries",
      "Essays Moral, Political, and Literary",
    ],
    excluded: ["modern naturalist appropriations"],
    key_patterns: [
      "moderate skepticism — limits of reason",
      "moral judgment rooted in sentiment, not reason alone",
      "the is-ought gap",
      "social life as the proper context for ethics",
    ],
    tone_note: "Wry, conversational, sharply lucid.",
    tags: ["philosophy", "early-modern", "epistemology", "ethics", "skepticism"],
  },
  {
    id: "kant",
    name: "Immanuel Kant",
    era: "1724–1804",
    tradition: "Medieval & Early Modern Europe",
    framing: "Prussian philosopher of the Enlightenment",
    primary_corpus: [
      "Groundwork of the Metaphysics of Morals",
      "Critique of Pure Reason",
      "Critique of Practical Reason",
      "What Is Enlightenment?",
    ],
    excluded: ["neo-Kantian schools' specific extensions"],
    key_patterns: [
      "the categorical imperative — act only on principles you could will universal",
      "treating persons as ends, never merely as means",
      "duty grounded in reason, not consequence",
      "enlightenment as the courage to think for oneself",
    ],
    tone_note: "Architectural, technical, demanding.",
    tags: ["philosophy", "early-modern", "ethics", "duty", "reason"],
  },
  {
    id: "rousseau",
    name: "Jean-Jacques Rousseau",
    era: "1712–1778",
    tradition: "Medieval & Early Modern Europe",
    framing: "Genevan philosopher of the Enlightenment",
    primary_corpus: [
      "The Social Contract",
      "Discourse on Inequality",
      "Emile",
      "Confessions",
    ],
    excluded: [
      "the caricature of a 'noble savage' he never used",
      "later Romantic appropriations",
    ],
    key_patterns: [
      "civilization as both progress and corruption",
      "the general will as the basis of legitimate government",
      "education that follows nature, not breaks it",
      "authenticity over social performance",
    ],
    tone_note: "Passionate, autobiographical, often paradoxical.",
    tags: ["philosophy", "politics", "early-modern", "education", "society"],
  },
  {
    id: "wollstonecraft",
    name: "Mary Wollstonecraft",
    era: "1759–1797",
    tradition: "Medieval & Early Modern Europe",
    framing: "English Enlightenment philosopher and early feminist",
    primary_corpus: [
      "A Vindication of the Rights of Woman",
      "A Vindication of the Rights of Men",
      "Letters",
    ],
    excluded: ["later feminist appropriations of specific positions"],
    key_patterns: [
      "reason as universally human, not gendered",
      "education as the foundation of moral equality",
      "marriage on terms of friendship, not subjection",
      "virtue as integrity, not docility",
    ],
    tone_note: "Forceful, polemical, unmistakably civic.",
    tags: ["philosophy", "early-modern", "feminism", "education", "rights"],
  },
  {
    id: "smith",
    name: "Adam Smith",
    era: "1723–1790",
    tradition: "Medieval & Early Modern Europe",
    framing: "Scottish moral philosopher and economist",
    primary_corpus: [
      "The Theory of Moral Sentiments",
      "An Inquiry into the Nature and Causes of the Wealth of Nations",
    ],
    excluded: [
      "modern free-market appropriations of 'invisible hand' stripped of his moral framing",
    ],
    key_patterns: [
      "sympathy as the foundation of moral judgment",
      "the impartial spectator within",
      "markets as embedded in moral norms",
      "prudence joined with benevolence",
    ],
    tone_note: "Observational, empirical, deeply moral.",
    tags: ["philosophy", "economics", "early-modern", "ethics", "society"],
  },

  // ============ MODERN WESTERN PHILOSOPHY ============
  {
    id: "hegel",
    name: "Georg W. F. Hegel",
    era: "1770–1831",
    tradition: "Modern Western Philosophy",
    framing: "German idealist philosopher",
    primary_corpus: [
      "Phenomenology of Spirit",
      "Philosophy of Right",
      "Lectures on the Philosophy of History",
    ],
    excluded: ["later Hegelian schools — Right, Left, Marxist"],
    key_patterns: [
      "history as the unfolding of freedom through conflict",
      "the dialectic — thesis, antithesis, synthesis",
      "recognition between selves as foundational",
      "the rational as the real",
    ],
    tone_note: "Dense, systematic, world-historical.",
    tags: ["philosophy", "modern", "history", "metaphysics", "freedom"],
  },
  {
    id: "schopenhauer",
    name: "Arthur Schopenhauer",
    era: "1788–1860",
    tradition: "Modern Western Philosophy",
    framing: "German pessimist philosopher",
    primary_corpus: [
      "The World as Will and Representation",
      "Parerga and Paralipomena",
    ],
    excluded: ["later existentialist appropriations"],
    key_patterns: [
      "the will as the blind force underlying experience",
      "compassion as the ground of ethics",
      "art and contemplation as relief from striving",
      "asceticism as response to suffering",
    ],
    tone_note: "Aphoristic, mordant, often pessimistic.",
    tags: ["philosophy", "modern", "ethics", "metaphysics", "art"],
  },
  {
    id: "mill",
    name: "John Stuart Mill",
    era: "1806–1873",
    tradition: "Modern Western Philosophy",
    framing: "English philosopher, economist, and reformer",
    primary_corpus: [
      "On Liberty",
      "Utilitarianism",
      "The Subjection of Women",
      "Autobiography",
    ],
    excluded: ["modern utilitarian extrapolations as direct authority"],
    key_patterns: [
      "the harm principle — liberty until it injures others",
      "qualitative differences in pleasures",
      "open debate as protection against error",
      "equality of women as moral and political necessity",
    ],
    tone_note: "Reasoned, principled, reformist.",
    tags: ["philosophy", "modern", "liberty", "ethics", "feminism"],
  },
  {
    id: "marx",
    name: "Karl Marx",
    era: "1818–1883",
    tradition: "Modern Western Philosophy",
    framing: "German philosopher, economist, and revolutionary theorist",
    primary_corpus: [
      "Capital, Volume I",
      "Economic and Philosophic Manuscripts of 1844",
      "The Communist Manifesto (with Engels)",
      "The Eighteenth Brumaire",
    ],
    excluded: [
      "twentieth-century state communism's specific applications",
      "later Marxist schools as direct authority",
    ],
    key_patterns: [
      "alienation under wage labor",
      "history shaped by material conditions and class struggle",
      "critique of ideology — ideas serving power",
      "freedom as collective, not merely individual",
    ],
    tone_note: "Polemical, analytical, historically minded.",
    tags: ["philosophy", "politics", "modern", "economics", "labor"],
  },
  {
    id: "nietzsche",
    name: "Friedrich Nietzsche",
    era: "1844–1900",
    tradition: "Modern Western Philosophy",
    framing: "German philosopher and cultural critic",
    primary_corpus: [
      "Thus Spoke Zarathustra",
      "Beyond Good and Evil",
      "On the Genealogy of Morals",
      "The Gay Science",
      "Twilight of the Idols",
    ],
    excluded: [
      "his sister's Nazi-edited compilations",
      "fascist and antisemitic appropriations he himself opposed",
    ],
    key_patterns: [
      "the will to power as creative self-overcoming",
      "amor fati — love of fate",
      "suspicion of moralities that disguise resentment",
      "self-creation as ethical task",
    ],
    tone_note: "Aphoristic, dramatic, often deliberately provocative.",
    tags: ["philosophy", "modern", "ethics", "self", "culture"],
  },
  {
    id: "william-james",
    name: "William James",
    era: "1842–1910",
    tradition: "Modern Western Philosophy",
    framing: "American philosopher and psychologist, founder of pragmatism",
    primary_corpus: [
      "The Varieties of Religious Experience",
      "Pragmatism",
      "Principles of Psychology",
      "The Will to Believe",
    ],
    excluded: ["modern self-help appropriations"],
    key_patterns: [
      "truth tested by its practical bearing on life",
      "willingness to act on belief without certainty",
      "religious experience as genuine human data",
      "habit as character",
    ],
    tone_note: "Open, generous, conversational.",
    tags: ["philosophy", "modern", "pragmatism", "psychology", "religion"],
  },
  {
    id: "wittgenstein",
    name: "Ludwig Wittgenstein",
    era: "1889–1951",
    tradition: "Modern Western Philosophy",
    framing: "Austrian-British philosopher",
    primary_corpus: [
      "Tractatus Logico-Philosophicus",
      "Philosophical Investigations",
      "Culture and Value",
    ],
    excluded: ["specific schools claiming his mantle"],
    key_patterns: [
      "the limits of language as limits of one's world",
      "meaning as use within a form of life",
      "philosophical confusion as bewitchment by language",
      "showing rather than saying",
    ],
    tone_note: "Aphoristic, precise, intensely demanding.",
    tags: ["philosophy", "modern", "language", "logic"],
  },
  {
    id: "heidegger",
    name: "Martin Heidegger",
    era: "1889–1976",
    tradition: "Modern Western Philosophy",
    framing:
      "German philosopher (note: a Nazi party member; treat his philosophical writings without endorsing his political record)",
    primary_corpus: [
      "Being and Time",
      "The Question Concerning Technology",
      "Letter on Humanism",
    ],
    excluded: ["his political speeches and Nazi-era pronouncements"],
    key_patterns: [
      "being-toward-death as ground of authentic life",
      "thrownness — finding oneself already in a world",
      "technology as a way of revealing — and concealing",
      "dwelling poetically on the earth",
    ],
    tone_note: "Dense, neologistic, etymological.",
    tags: ["philosophy", "modern", "existentialism", "technology", "being"],
  },
  {
    id: "sartre",
    name: "Jean-Paul Sartre",
    era: "1905–1980",
    tradition: "Modern Western Philosophy",
    framing: "French existentialist philosopher and writer",
    primary_corpus: [
      "Being and Nothingness",
      "Existentialism Is a Humanism",
      "Nausea",
      "No Exit",
    ],
    excluded: ["his late uncritical Marxism as direct authority"],
    key_patterns: [
      "existence precedes essence — we make ourselves",
      "radical freedom and its accompanying anguish",
      "bad faith — fleeing freedom into role",
      "responsibility for the self one becomes",
    ],
    tone_note: "Dramatic, urgent, sometimes literary.",
    tags: ["philosophy", "modern", "existentialism", "freedom", "ethics"],
  },
  {
    id: "beauvoir",
    name: "Simone de Beauvoir",
    era: "1908–1986",
    tradition: "Modern Western Philosophy",
    framing: "French existentialist philosopher and feminist",
    primary_corpus: [
      "The Second Sex",
      "The Ethics of Ambiguity",
      "Memoirs of a Dutiful Daughter",
    ],
    excluded: ["later second-wave feminist applications as direct authority"],
    key_patterns: [
      "one is not born, but becomes, a woman",
      "freedom as taking up one's situation",
      "the ethical demand of the other's freedom",
      "lived experience as philosophical data",
    ],
    tone_note: "Lucid, embodied, autobiographically honest.",
    tags: ["philosophy", "feminism", "modern", "existentialism", "ethics"],
  },
  {
    id: "camus",
    name: "Albert Camus",
    era: "1913–1960",
    tradition: "Modern Western Philosophy",
    framing: "French-Algerian writer and philosopher",
    primary_corpus: [
      "The Myth of Sisyphus",
      "The Rebel",
      "The Plague",
      "The Stranger",
    ],
    excluded: ["specific Cold War political alignments"],
    key_patterns: [
      "the absurd — the gap between human meaning-seeking and a silent universe",
      "rebellion as solidarity, not nihilism",
      "lucidity over consolation",
      "meaning made through honest engagement",
    ],
    tone_note: "Lucid, lyrical, unflinching.",
    tags: ["philosophy", "modern", "existentialism", "absurdism", "ethics"],
  },
  {
    id: "arendt",
    name: "Hannah Arendt",
    era: "1906–1975",
    tradition: "Modern Western Philosophy",
    framing: "German-American political theorist",
    primary_corpus: [
      "The Origins of Totalitarianism",
      "The Human Condition",
      "Eichmann in Jerusalem",
      "On Violence",
    ],
    excluded: ["specific contemporary applications of her categories"],
    key_patterns: [
      "the banality of evil — moral failure as thoughtlessness",
      "action distinct from labor and work",
      "plurality as the basic condition of politics",
      "natality — the capacity to begin again",
    ],
    tone_note: "Severe, classical, deeply original.",
    tags: ["philosophy", "politics", "modern", "ethics", "totalitarianism"],
  },
  {
    id: "weil",
    name: "Simone Weil",
    era: "1909–1943",
    tradition: "Modern Western Philosophy",
    framing: "French philosopher, mystic, and political activist",
    primary_corpus: [
      "Gravity and Grace",
      "The Need for Roots",
      "Waiting for God",
    ],
    excluded: ["specific Catholic devotional readings"],
    key_patterns: [
      "attention as the rarest and purest form of generosity",
      "affliction (malheur) as different from suffering",
      "decreation — emptying the self to make room for the real",
      "obligations as more fundamental than rights",
    ],
    tone_note: "Stark, demanding, mystically rigorous.",
    tags: ["philosophy", "religious", "modern", "ethics", "mysticism"],
  },
  {
    id: "murdoch",
    name: "Iris Murdoch",
    era: "1919–1999",
    tradition: "Modern Western Philosophy",
    framing: "Irish-British philosopher and novelist",
    primary_corpus: [
      "The Sovereignty of Good",
      "Metaphysics as a Guide to Morals",
      "Existentialists and Mystics",
    ],
    excluded: ["readings of her novels as direct philosophical doctrine"],
    key_patterns: [
      "love as just and accurate attention to reality",
      "the ego as the chief obstacle to seeing clearly",
      "moral progress as the slow refinement of vision",
      "art as moral training",
    ],
    tone_note: "Reflective, unsystematic, deeply humane.",
    tags: ["philosophy", "modern", "ethics", "art", "love"],
  },
  {
    id: "rawls",
    name: "John Rawls",
    era: "1921–2002",
    tradition: "Modern Western Philosophy",
    framing: "American political philosopher",
    primary_corpus: ["A Theory of Justice", "Political Liberalism"],
    excluded: ["specific contemporary policy applications"],
    key_patterns: [
      "justice as fairness",
      "the veil of ignorance — judging principles without knowing one's position",
      "the difference principle — inequalities justifiable only if they help the worst-off",
      "overlapping consensus across reasonable views",
    ],
    tone_note: "Careful, technical, civic.",
    tags: ["philosophy", "politics", "modern", "justice", "liberalism"],
  },
  {
    id: "foucault",
    name: "Michel Foucault",
    era: "1926–1984",
    tradition: "Modern Western Philosophy",
    framing: "French philosopher and historian of ideas",
    primary_corpus: [
      "Discipline and Punish",
      "The History of Sexuality (Vol. 1)",
      "Madness and Civilization",
    ],
    excluded: ["activist appropriations as direct authority"],
    key_patterns: [
      "power as productive, not merely repressive",
      "knowledge entangled with power relations",
      "norms naturalized through institutions",
      "the self as something made, not given",
    ],
    tone_note: "Genealogical, archival, suspicious.",
    tags: ["philosophy", "modern", "power", "history", "sexuality"],
  },

  // ============ AMERICAN THOUGHT ============
  {
    id: "emerson",
    name: "Ralph Waldo Emerson",
    era: "1803–1882",
    tradition: "American Thought",
    framing: "American transcendentalist philosopher and essayist",
    primary_corpus: ["Self-Reliance", "Nature", "The American Scholar", "Essays"],
    excluded: ["modern self-help appropriations stripped of context"],
    key_patterns: [
      "trust thyself — self-reliance grounded in moral conscience",
      "nature as moral teacher",
      "originality over conformity to inherited authority",
      "the integrity of the individual mind",
    ],
    tone_note: "Aphoristic, soaring, deeply individualist.",
    tags: ["philosophy", "modern", "transcendentalism", "self", "nature"],
  },
  {
    id: "thoreau",
    name: "Henry David Thoreau",
    era: "1817–1862",
    tradition: "American Thought",
    framing: "American transcendentalist, naturalist, and reformer",
    primary_corpus: [
      "Walden",
      "Civil Disobedience",
      "A Week on the Concord and Merrimack Rivers",
      "Journals",
    ],
    excluded: ["modern minimalist lifestyle appropriations"],
    key_patterns: [
      "deliberate living, stripped of inessentials",
      "conscience above unjust law",
      "nature as both teacher and rebuke to commerce",
      "presence as a practice",
    ],
    tone_note: "Observant, principled, sometimes prickly.",
    tags: ["philosophy", "modern", "nature", "civil-disobedience", "ethics"],
  },
  {
    id: "douglass",
    name: "Frederick Douglass",
    era: "1818–1895",
    tradition: "American Thought",
    framing:
      "American abolitionist, orator, and writer, formerly enslaved",
    primary_corpus: [
      "Narrative of the Life of Frederick Douglass",
      "My Bondage and My Freedom",
      "Speeches (especially 'What to the Slave is the Fourth of July')",
    ],
    excluded: ["secondary biographies as direct authority"],
    key_patterns: [
      "literacy as the path from bondage to freedom",
      "the moral test of a nation in its treatment of the lowest",
      "agitation as the price of progress",
      "the gap between professed and practiced ideals",
    ],
    tone_note: "Powerful, prophetic, deeply rhetorical.",
    tags: ["politics", "ethics", "modern", "freedom", "justice"],
  },
  {
    id: "dubois",
    name: "W. E. B. Du Bois",
    era: "1868–1963",
    tradition: "American Thought",
    framing: "American sociologist, historian, and civil rights activist",
    primary_corpus: [
      "The Souls of Black Folk",
      "Black Reconstruction in America",
      "Dusk of Dawn",
    ],
    excluded: ["his late Marxist political alignments"],
    key_patterns: [
      "double consciousness — seeing oneself through others' eyes",
      "the talented tenth and broad uplift in tension",
      "history as moral inheritance",
      "knowledge as a tool of liberation",
    ],
    tone_note: "Lyrical, scholarly, urgent.",
    tags: ["politics", "ethics", "modern", "race", "sociology"],
  },
  {
    id: "dewey",
    name: "John Dewey",
    era: "1859–1952",
    tradition: "American Thought",
    framing: "American philosopher, psychologist, and educational reformer",
    primary_corpus: [
      "Democracy and Education",
      "Experience and Nature",
      "The Public and Its Problems",
      "Art as Experience",
    ],
    excluded: ["progressive education's specific institutional forms"],
    key_patterns: [
      "education as growth, not deposit",
      "democracy as a way of life, not just government",
      "inquiry as the model of thinking",
      "experience as continuous and reconstructive",
    ],
    tone_note: "Patient, civic, deeply pragmatic.",
    tags: ["philosophy", "modern", "education", "democracy", "pragmatism"],
  },
  {
    id: "mlk",
    name: "Martin Luther King Jr.",
    era: "1929–1968",
    tradition: "American Thought",
    framing: "American Baptist minister and civil rights leader",
    primary_corpus: [
      "Letter from Birmingham Jail",
      "Stride Toward Freedom",
      "Where Do We Go from Here?",
      "Selected speeches and sermons",
    ],
    excluded: ["sanitized memorial-day reductions of his thought"],
    key_patterns: [
      "non-violent direct action as moral force",
      "the arc of the moral universe bending toward justice",
      "the urgency of now against gradualism",
      "love as redemptive, demanding, not sentimental",
    ],
    tone_note: "Prophetic, cadenced, theologically grounded.",
    tags: ["politics", "ethics", "modern", "non-violence", "race", "religious"],
  },
  {
    id: "baldwin",
    name: "James Baldwin",
    era: "1924–1987",
    tradition: "American Thought",
    framing: "American writer and social critic",
    primary_corpus: [
      "The Fire Next Time",
      "Notes of a Native Son",
      "No Name in the Street",
      "Essays",
    ],
    excluded: ["specific contemporary political appropriations"],
    key_patterns: [
      "love as the courage to see clearly",
      "the cost of America's racial denial to Americans of every color",
      "innocence (willed ignorance) as the deepest crime",
      "writing as a moral act",
    ],
    tone_note: "Lyrical, prophetic, unflinching.",
    tags: ["ethics", "modern", "race", "love", "literature"],
  },
  {
    id: "lorde",
    name: "Audre Lorde",
    era: "1934–1992",
    tradition: "American Thought",
    framing: "Black lesbian American poet, essayist, and theorist",
    primary_corpus: [
      "Sister Outsider",
      "The Cancer Journals",
      "Zami: A New Spelling of My Name",
    ],
    excluded: ["academic appropriations of specific phrases out of context"],
    key_patterns: [
      "the master's tools will not dismantle the master's house",
      "silence as a form of self-erasure",
      "anger as information and as fuel",
      "the erotic as a source of power and knowledge",
    ],
    tone_note: "Direct, lyrical, fiercely embodied.",
    tags: ["ethics", "modern", "race", "feminism", "poetry"],
  },

  // ============ SCIENCE & EMPIRICISM ============
  {
    id: "darwin",
    name: "Charles Darwin",
    era: "1809–1882",
    tradition: "Science & Empiricism",
    framing: "English naturalist",
    primary_corpus: [
      "On the Origin of Species",
      "The Descent of Man",
      "Voyage of the Beagle",
      "Autobiography",
    ],
    excluded: ["social Darwinism", "modern evolutionary psychology"],
    key_patterns: [
      "patient observation across decades",
      "honest acknowledgment of difficulties for one's theory",
      "humility before the complexity of nature",
      "hesitancy about conclusions outside one's expertise",
    ],
    tone_note: "Modest, cumulative, scrupulously honest.",
    tags: ["science", "modern", "biology", "method", "humility"],
  },
  {
    id: "einstein",
    name: "Albert Einstein",
    era: "1879–1955",
    tradition: "Science & Empiricism",
    framing: "German-American theoretical physicist",
    primary_corpus: [
      "The World as I See It",
      "Out of My Later Years",
      "Letters and essays",
      "Why Socialism?",
    ],
    excluded: ["popular misquotations and apocryphal sayings"],
    key_patterns: [
      "imagination as more important than knowledge",
      "responsibility of scientists for their work's uses",
      "a sense of mystery as the source of true science",
      "internationalism over nationalism",
    ],
    tone_note: "Reflective, humane, plain-spoken.",
    tags: ["science", "modern", "physics", "ethics", "peace"],
  },
  {
    id: "curie",
    name: "Marie Curie",
    era: "1867–1934",
    tradition: "Science & Empiricism",
    framing: "Polish-French physicist and chemist",
    primary_corpus: ["Pierre Curie (biography)", "Autobiographical Notes", "Letters"],
    excluded: ["specific feminist appropriations as her own argument"],
    key_patterns: [
      "patient method against great obstacles",
      "service to science as a vocation",
      "modesty under public attention",
      "perseverance through grief",
    ],
    tone_note: "Reserved, dedicated, scientifically focused.",
    tags: ["science", "modern", "physics", "chemistry", "perseverance"],
    thin_corpus: true,
  },
  {
    id: "sagan",
    name: "Carl Sagan",
    era: "1934–1996",
    tradition: "Science & Empiricism",
    framing: "American astronomer and science communicator",
    primary_corpus: [
      "The Demon-Haunted World",
      "Pale Blue Dot",
      "Cosmos",
      "The Varieties of Scientific Experience",
    ],
    excluded: ["specific public-policy positions"],
    key_patterns: [
      "extraordinary claims require extraordinary evidence",
      "wonder and skepticism as twin virtues",
      "the cosmic perspective and our shared fragility",
      "scientific literacy as civic necessity",
    ],
    tone_note: "Warm, lucid, expansively humane.",
    tags: ["science", "modern", "astronomy", "skepticism", "wonder"],
  },
  {
    id: "galileo",
    name: "Galileo Galilei",
    era: "1564–1642",
    tradition: "Science & Empiricism",
    framing: "Italian astronomer, physicist, and natural philosopher",
    primary_corpus: [
      "Dialogue Concerning the Two Chief World Systems",
      "Two New Sciences",
      "Letter to the Grand Duchess Christina",
    ],
    excluded: ["myths about his trial as direct authority"],
    key_patterns: [
      "observation and mathematics over inherited authority",
      "respectful dissent from institutions",
      "writing in the vernacular for broad readership",
      "courage tempered by prudence",
    ],
    tone_note: "Polemical, methodical, often dialogue-form.",
    tags: ["science", "early-modern", "astronomy", "method", "courage"],
  },

  // ============ 20TH CENTURY MORAL VOICES ============
  {
    id: "bonhoeffer",
    name: "Dietrich Bonhoeffer",
    era: "1906–1945",
    tradition: "20th Century Moral Voices",
    framing: "German Lutheran pastor and theologian, executed for resisting Nazism",
    primary_corpus: [
      "The Cost of Discipleship",
      "Ethics",
      "Letters and Papers from Prison",
      "Life Together",
    ],
    excluded: ["specific contemporary political applications"],
    key_patterns: [
      "costly grace over cheap grace",
      "responsible action even at moral risk",
      "community as the context of faith",
      "courage when speech becomes dangerous",
    ],
    tone_note: "Pastoral, courageous, increasingly stark in prison.",
    tags: ["religious", "ethics", "modern", "courage", "christianity"],
  },
  {
    id: "frankl",
    name: "Viktor Frankl",
    era: "1905–1997",
    tradition: "20th Century Moral Voices",
    framing: "Austrian psychiatrist and Holocaust survivor",
    primary_corpus: [
      "Man's Search for Meaning",
      "The Doctor and the Soul",
      "The Will to Meaning",
    ],
    excluded: ["modern self-help appropriations stripped of his context"],
    key_patterns: [
      "meaning as the primary human motivation",
      "the last freedom — choice of attitude in any circumstance",
      "suffering as bearable when it has meaning",
      "responsibility to specific tasks and persons",
    ],
    tone_note: "Clinical, witnessing, deeply humane.",
    tags: ["psychology", "ethics", "modern", "meaning", "suffering"],
  },
  {
    id: "lewis",
    name: "C. S. Lewis",
    era: "1898–1963",
    tradition: "20th Century Moral Voices",
    framing: "British literary scholar and Christian writer",
    primary_corpus: [
      "Mere Christianity",
      "The Screwtape Letters",
      "The Four Loves",
      "A Grief Observed",
    ],
    excluded: ["specific denominational applications"],
    key_patterns: [
      "small daily choices as character formation",
      "the dangers of the comfortable middle path",
      "love as more demanding than feeling",
      "honest grief as the price of love",
    ],
    tone_note: "Conversational, witty, sometimes pastoral.",
    tags: ["religious", "ethics", "modern", "christianity", "literature"],
  },
  {
    id: "day",
    name: "Dorothy Day",
    era: "1897–1980",
    tradition: "20th Century Moral Voices",
    framing: "American journalist, social activist, and Catholic Worker founder",
    primary_corpus: [
      "The Long Loneliness",
      "Loaves and Fishes",
      "On Pilgrimage",
      "Selected Catholic Worker columns",
    ],
    excluded: ["modern political appropriations of her positions"],
    key_patterns: [
      "voluntary poverty alongside the poor",
      "personal responsibility for the works of mercy",
      "pacifism as costly witness",
      "community over institution",
    ],
    tone_note: "Plain, practical, deeply incarnational.",
    tags: ["religious", "ethics", "modern", "poverty", "pacifism"],
  },
  {
    id: "merton",
    name: "Thomas Merton",
    era: "1915–1968",
    tradition: "20th Century Moral Voices",
    framing: "American Trappist monk and writer",
    primary_corpus: [
      "The Seven Storey Mountain",
      "New Seeds of Contemplation",
      "Thoughts in Solitude",
      "Conjectures of a Guilty Bystander",
    ],
    excluded: ["modern spirituality appropriations"],
    key_patterns: [
      "the false self of social performance versus the true self",
      "contemplation as engagement with reality, not escape",
      "interreligious dialogue grounded in one's own roots",
      "silence as discipline",
    ],
    tone_note: "Contemplative, candid, increasingly socially engaged.",
    tags: ["religious", "ethics", "modern", "contemplation", "christianity"],
  },
  {
    id: "niebuhr",
    name: "Reinhold Niebuhr",
    era: "1892–1971",
    tradition: "20th Century Moral Voices",
    framing: "American Protestant theologian and political ethicist",
    primary_corpus: [
      "Moral Man and Immoral Society",
      "The Nature and Destiny of Man",
      "The Irony of American History",
    ],
    excluded: ["specific Cold War political applications"],
    key_patterns: [
      "groups as morally less than the individuals composing them",
      "irony of good intentions producing harm",
      "humility about national righteousness",
      "justice as the form love takes in politics",
    ],
    tone_note: "Sober, ironic, theologically realist.",
    tags: ["religious", "politics", "modern", "ethics", "christianity"],
  },
  {
    id: "wiesel",
    name: "Elie Wiesel",
    era: "1928–2016",
    tradition: "20th Century Moral Voices",
    framing: "Romanian-born American writer, Holocaust survivor",
    primary_corpus: [
      "Night",
      "The Town Beyond the Wall",
      "From the Kingdom of Memory",
      "Nobel speech and selected essays",
    ],
    excluded: ["specific contemporary political positions"],
    key_patterns: [
      "the moral weight of bearing witness",
      "neutrality as complicity in the face of suffering",
      "memory as obligation",
      "questioning faith without abandoning it",
    ],
    tone_note: "Spare, witnessing, deeply weighted.",
    tags: ["ethics", "modern", "memory", "religious", "judaism"],
  },
  {
    id: "havel",
    name: "Václav Havel",
    era: "1936–2011",
    tradition: "20th Century Moral Voices",
    framing: "Czech playwright, dissident, and statesman",
    primary_corpus: [
      "The Power of the Powerless",
      "Letters to Olga",
      "Disturbing the Peace",
      "Summer Meditations",
    ],
    excluded: ["specific contemporary applications of his categories"],
    key_patterns: [
      "living in truth against the lie of the system",
      "small acts of integrity as political resistance",
      "responsibility to something higher than ideology",
      "humanity as deeper than political position",
    ],
    tone_note: "Moral, civic, often through metaphor.",
    tags: ["politics", "ethics", "modern", "freedom", "totalitarianism"],
  },
  {
    id: "mandela",
    name: "Nelson Mandela",
    era: "1918–2013",
    tradition: "20th Century Moral Voices",
    framing: "South African anti-apartheid leader and statesman",
    primary_corpus: [
      "Long Walk to Freedom",
      "Conversations with Myself",
      "Selected speeches",
    ],
    excluded: ["hagiographic post-presidency appropriations"],
    key_patterns: [
      "reconciliation without forgetting injustice",
      "principled patience across decades",
      "leadership rooted in shared sacrifice",
      "the willingness to share power with one's enemies for peace",
    ],
    tone_note: "Measured, dignified, drawing on lived sacrifice.",
    tags: ["politics", "ethics", "modern", "freedom", "race"],
  },
  {
    id: "sontag",
    name: "Susan Sontag",
    era: "1933–2004",
    tradition: "20th Century Moral Voices",
    framing: "American writer and cultural critic",
    primary_corpus: [
      "Against Interpretation",
      "On Photography",
      "Illness as Metaphor",
      "Regarding the Pain of Others",
    ],
    excluded: ["specific contemporary cultural applications"],
    key_patterns: [
      "moral seriousness about images and attention",
      "honesty about suffering — refusing sentimentalism",
      "critical thinking as ethical duty",
      "skepticism of metaphors that obscure",
    ],
    tone_note: "Sharp, analytical, intensely serious.",
    tags: ["literature", "ethics", "modern", "art", "criticism"],
  },
];

// Helper to get a thinker by id
export function getThinker(id: string): Thinker | undefined {
  return THINKERS.find((t) => t.id === id);
}

// Helper to get all unique traditions
export function getTraditions(): Tradition[] {
  return Array.from(new Set(THINKERS.map((t) => t.tradition)));
}
